### ISSUE TITLE
Request for wafv2_{rule_group,web_acl,web_acl_association,web_acl_logging_configuration} resources

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane-contrib/provider-upjet-aws#1019]
### What resource do you need?
From the list of Terraform supported resources, some are still missing from `provider-aws-wafv2`:

[ aws_wafv2_ip_set ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set):white_check_mark:
[ aws_wafv2_regex_pattern_set ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set):white_check_mark:
[ aws_wafv2_rule_group ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group):question:
[ aws_wafv2_web_acl ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl):question:
[ aws_wafv2_web_acl_association ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association):question:
[ aws_wafv2_web_acl_logging_configuration ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration):question:

Terraform Resource Name: 

- aws_wafv2_rule_group
- aws_wafv2_web_acl
- aws_wafv2_web_acl_association
- aws_wafv2_web_acl_logging_configuration

### What is your use case?

Cannot deploy WAFv2 resources without leveraging `provider-terraform`, and the latter is still limited (e.g. does not support SSH authentication to fetch external modules).

**Comment by haarchri** [comment]
`aws_wafv2_rule_group` CRD `55MB` 
`aws_wafv2_web_acl`  with `68MB`

we will hit `cannot establish control of object: Request entity too large: limit is 3145728`
Draft PR: https://github.com/upbound/provider-aws/pull/1032 to highlight the issue 
```
du -ah  | sort -hr
153M	.
 68M	./wafv2.aws.upbound.io_webacls.yaml
 55M	./wafv2.aws.upbound.io_rulegroups.yaml
548K	./medialive.aws.upbound.io_channels.yaml
344K	./firehose.aws.upbound.io_deliverystreams.yaml
280K	./securityhub.aws.upbound.io_insights.yaml
232K	./appflow.aws.upbound.io_flows.yaml
200K	./appmesh.aws.upbound.io_virtualnodes.yaml
184K	./kinesisanalyticsv2.aws.upbound.io_applications.yaml
180K	./appmesh.aws.upbound.io_routes.yaml
176K	./autoscaling.aws.upbound.io_autoscalinggroups.yaml
168K	./kendra.aws.upbound.io_datasources.yaml
168K	./ec2.aws.upbound.io_launchtemplates.yaml
[...]
 16K	./cloudwatchevents.aws.upbound.io_buses.yaml
 16K	./cloudwatch.aws.upbound.io_dashboards.yaml
 16K	./backup.aws.upbound.io_globalsettings.yaml
 16K	./accessanalyzer.aws.upbound.io_analyzers.yaml
 12K	./aws.upbound.io_storeconfigs.yaml
8.0K	./aws.upbound.io_providerconfigusages.yaml
```

**Comment by david-shato-sisense** [comment]
really waiting for this implementation.
any updates?

**Comment by MichaelRSilva** [comment]
Any update about this implementation?
