### ISSUE TITLE
StoreConfig Vault example configuration non working and misleading 

### ISSUE THREAD

**Issue by gladio78** [crossplane-contrib/provider-upjet-aws#1033]
As per title the StoreConfig example for vault is not working on 0.46.0 provider 
https://github.com/upbound/provider-aws/blob/main/examples/storeconfig/vault.yaml

_Error from server (BadRequest): error when creating "vault-storeconfig.yaml": StoreConfig in version "v1alpha1" cannot be handled as a StoreConfig: strict decoding error: unknown field "spec.vault"_

**Comment by haarchri** [comment]
`spec.vault` is not in schema since `v0.41.0`

https://marketplace.upbound.io/providers/upbound/provider-family-aws/v0.40.0/resources/aws.upbound.io/StoreConfig/v1alpha1
vs.
https://marketplace.upbound.io/providers/upbound/provider-family-aws/v0.41.0/resources/aws.upbound.io/StoreConfig/v1alpha1

**Comment by turkenf** [comment]
I am closing this since the specified field deprecated.

**Comment by haarchri** [comment]
@turkenf but the example is outdated https://github.com/upbound/provider-aws/blob/main/examples/storeconfig/vault.yaml we need to update the example
