### ISSUE TITLE
Unable to change DynamoDB billing mode from On-demand to PROVISIONED when using GSI

### ISSUE THREAD

**Issue by 7navyasa** [crossplane-contrib/provider-upjet-aws#1041]
### What happened?
When updating a DynamoDB table with one or more global secondary indexes, changing billing_mode from PAY_PER_REQUEST to PROVISIONED, the change doesnot apply. The GSI index read & write capacity gets updated to the desired values in the Composite Resource but the values show up as "0" capacity in the Managed Resource which makes it fail due to invalid parameter.

Message: 

>failed: updating Amazon DynamoDB Table (crossplane-ups-adapter):
      ValidationException: One or more parameter values were invalid: ProvisionedThroughput
      must be specified for index: index-A,index-B\n\tstatus code:
      400, request id: CA1UOUUVQFB1FFAOTUCVTLLF4NVV4KQNSO5AEMVJF66Q9ASUAAJG: "

### How can we reproduce it?

- Create a Dynamodb table with PAY_PER_REQUEST billing mode and global index (I have been using 2 GSI's). 
- Once created change the billing mode to PROVISIONED and assign read & write capacity to the table and GSI.
### What environment did it happen in?

* Crossplane Version: v1.13.2 and v1.14.4
* Provider Version: v0.40.0 and v0.46.1
* Kubernetes Version: v1.27.8  
* Kubernetes Distribution: EKS

**Comment by mbbush** [comment]
Hi @7navyasa,

Could you please include manifests for the resource both before and after update, to make it easier for those of us not as familiar with dynamodb to reproduce it?

**Comment by 7navyasa** [comment]
[dynamodb.zip](https://github.com/upbound/provider-aws/files/13857038/dynamodb.zip)
Hi @mbbush, here are the manifest to reproduce the issue

**Comment by turkenf** [comment]
Hi @7navyasa,

Thank you for raising this but I could not reproduce this issue with the provided information. 

- Applied following:
```
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: example-ft
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta1/table
spec:
  forProvider:
    region: us-west-1
    attribute:
    - name: UserId
      type: S
    - name: UserName
      type: S
    - name: Pass
      type: B
    billingMode: PAY_PER_REQUEST
    globalSecondaryIndex:
    - hashKey: UserName
      name: UserNameIndex
      nonKeyAttributes:
      - UserId
      projectionType: INCLUDE
      rangeKey: Pass
    hashKey: UserId
    rangeKey: Pass
    tags:
      Environment: production
      Name: dynamodb-table-1
```
- Then I can configure it successfully according to the following:
```
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: example-ft
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta1/table
spec:
  forProvider:
    region: us-west-1
    attribute:
    - name: UserId
      type: S
    - name: UserName
      type: S
    - name: Pass
      type: B
    billingMode: PROVISIONED
    globalSecondaryIndex:
    - hashKey: UserName
      name: UserNameIndex
      nonKeyAttributes:
      - UserId
      projectionType: INCLUDE
      rangeKey: Pass
      readCapacity: 10
      writeCapacity: 10
    readCapacity: 20
    writeCapacity: 20
    hashKey: UserId
    rangeKey: Pass
    tags:
      Environment: production
      Name: dynamodb-table-1
```

Please try it with these examples and let us know if it works.
