### ISSUE TITLE
Request for `aws_route53_key_signing_key` resource

### ISSUE THREAD

**Issue by duizabojul** [crossplane-contrib/provider-upjet-aws#1044]
### What resource do you need?

We need `aws_route53_key_signing_key` resource. I already use this resource successfully on a fork, so it should be pretty straightforward.

### What is your use case?

Enable DNSSEC on our domains

**Comment by turkenf** [comment]
@duizabojul, thank you for raising this, we would be happy if you would like to contribute. This [guide](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-short.md) will help you.
