### ISSUE TITLE
Using private registry for aws family of providers causes package errors and fails to bring up the provider

### ISSUE THREAD

**Issue by arunpmohan** [crossplane-contrib/provider-upjet-aws#1082]
We wanted to use upbound providers from our own private docker registry and we were using aws ECR for this. So essential what we did is pulled all upbound images and pushed to ECR following the same technique here.

Let us just take one example here.

docker pull xpkg.upbound.io/upbound/provider-family-aws:v0.47.0
docker tag xpkg.upbound.io/upbound/provider-family-aws:v0.47.0 awsecr/upbound/provider-family-aws:v0.47.0
docker push awsecr/upbound/provider-family-aws:v0.47.0

Provider Yaml
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
spec:
  package: <accoundid>.dkr.ecr.us-east-1.amazonaws.com/upbound/provider-family-aws:v0.47.0
#  package: xpkg.upbound.io/upbound/provider-family-aws:v0.47.0
  skipDependencyResolution: true
```
We deployed this provider by applying the above yaml.

Now this wont bring up the provider at all because we get this error on describing the pkgrev

```
  Type     Reason           Age                From                                         Message
  ----     ------           ----               ----                                         -------
  Warning  BindClusterRole  19m                rbac/providerrevision.pkg.crossplane.io      cannot apply ClusterRoleBinding: cannot create object: clusterrolebindings.rbac.authorization.k8s.io "crossplane:provider:upbound-provider-family-aws-2be3c07a00d3:system" already exists
  Normal   BindClusterRole  19m (x3 over 19m)  rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole "crossplane:provider:upbound-provider-family-aws-2be3c07a00d3:system" to provider ServiceAccount(s):
  Warning  ParsePackage     89s (x6 over 16m)  packages/providerrevision.pkg.crossplane.io  cannot initialize parser backend: couldn't find "package.yaml" file after checking 1 files in the archive (annotated layer: false): context deadline exceeded

```

**If we deploy the provider by directly pulling from upbound repos then they work fine.**

### What environment did it happen in?

* Crossplane Version: 1.14.5.1
* Provider Version: 1.47.0
* Kubernetes Version: 1.28
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
Please Check this: https://github.com/crossplane/crossplane/issues/4299#issuecomment-1691379712
