### ISSUE TITLE
Support MWAA Environments (AWS Managed Airflow)

### ISSUE THREAD

**Issue by applike-ss** [crossplane-contrib/provider-upjet-aws#1093]
### What problem are you facing?

We would like to manage MWAA Environments (AWS Managed Airflow) via this provider, however the resource does not exist yet.

### How could Official AWS Provider help solve your problem?

Implementation of said resource would help 👍 

### References
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mwaa_environment
https://docs.aws.amazon.com/mwaa/latest/API/Welcome.html
https://docs.aws.amazon.com/mwaa/latest/userguide/what-is-mwaa.html

**Comment by turkenf** [comment]
@applike-ss, thank you for raising this. We would appreciate it if you would like to contribute, [this guide](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-short.md) may help you.
