### ISSUE TITLE
SecurityGroupRule adding additional cidrBlocks does not work

### ISSUE THREAD

**Issue by Donimax** [crossplane-contrib/provider-upjet-aws#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

SecurityGroupRule.ec2.aws.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: testing-vpc
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 172.16.0.0/16
    tags:
      Name: testingVpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    testing.upbound.io/example-name: securitygroup1
  name: securitygroup1
spec:
  forProvider:
    description: test
    name: test
    region: us-west-1
    tags:
      Name: test
    vpcIdRef:
      name: testing-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: test
spec:
  forProvider:
    cidrBlocks:
      - 10.0.0.0/16
    fromPort: 0
    protocol: tcp
    region: us-west-1
    securityGroupIdRef:
      name: securitygroup1
    toPort: 65535
    type: ingress
```

### Steps to Reproduce

- Create VPC
- Create SecurityGroup
- Create SecurityGroupRule which is attached to SecurityGroup with cidrBlocks:
```
    cidrBlocks:
      - 10.0.0.0/16
```

- Wait until all is ready
- Add additional cidr to SecurityGroupRule:
```
    cidrBlocks:
      - 10.0.0.0/16
      - 192.168.1.0/24
```

### What happened?

After adding an additional cidr block to the ready SecurityGroupRule, the rule is not updated and an error is reported.

### Relevant Error Output Snippet

```shell
async update failed: refuse to update the external resource: cannot change the value of the argument "cidr_blocks.#" from "1" to "2"
```

### Crossplane Version

1.14.5-up.1

### Provider Version

0.47.1

### Kubernetes Version

v1.28.3

### Kubernetes Distribution

EKS

**Comment by ytsarev** [comment]
@Donimax thanks a lot for the detailed reproducer! 

To unblock yourself, could you try to use alternative resources https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v0.47.1/resources/ec2.aws.upbound.io/SecurityGroupIngressRule/v1beta1 and https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v0.47.1/resources/ec2.aws.upbound.io/SecurityGroupEgressRule/v1beta1 .

They might work better in this scenario.

**Comment by Donimax** [comment]
@ytsarev 
I am familiar with securityGroupIngress/EgressRule and understand that it may serve as a temporary solution. However, using securityGroupIngressRule would result in 54 rules in the our smallest setup, compared to only 10 securitygrouprule. This is because only one CIDR can be specified per SecurityGroupIngressRule. In a typical deployment from us, there would be 171 or much more rules.

**Comment by ytsarev** [comment]
@Donimax, the error output here is confusing, it looks like we cannot update `cidrBlocks` without resource recreation, see underlying https://github.com/hashicorp/terraform-provider-aws/blob/9e9a0fb71f3e25bd68d6dc9199c8913acc6b6f88/internal/service/ec2/vpc_security_group_rule.go#L50 where we have `ForceNew` on the field.


>  This is because only one CIDR can be specified per SecurityGroupIngressRule
It looks like it is in line with what is happening on the AWS API side where these requests are also granular https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CidrBlock.html, https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroupRuleUpdate.html, https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroupRuleRequest.html. 

It is also in line with Crossplane Resource Model, High Fidelity concept: https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md#high-fidelity

I suggest abstracting SecurityGroupIngressRule creation with custom XRD + Composition. This way you will not directly be exposed to the mass number of Managed Resources.

**Comment by haarchri** [comment]
Take a look here: https://github.com/upbound/configuration-aws-securitygroup
