### ISSUE TITLE
Request for `aws_eks_access_entry ` resource

### ISSUE THREAD

**Issue by siddharthdeshmukh** [crossplane-contrib/provider-upjet-aws#1098]
### What resource do you need?

Terraform Resource Name: aws_eks_access_entry, aws_eks_access_policy_association

### What is your use case?

Recently AWS EKS launched simplified Kubernetes Access to replace authentication via `aws-auth` configmap.
https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/

This feature was recently [released](https://github.com/hashicorp/terraform-provider-aws/issues/34982) in Terraform

**Comment by turkenf** [comment]
@siddharthdeshmukh, thank you for raising this issue. As you mentioned, these resources are available with Terraform version `5.33.0`. 

We are currently using version [5.31.0](https://github.com/upbound/provider-aws/blob/88c1ae1d25dd145ddcb9149769cc4de590494c39/Makefile#L11C38-L11C44) on the main branch, these resources will be configurable and available when we bump terraform version `5.33.0` and later.

**Comment by geowalrus4gh** [comment]
Any plan to bump to 5.33.0+? The latest provider has reached 5.40.0.
