### ISSUE TITLE
[Bug]:  How do I force redeployment of my ApiGateway

### ISSUE THREAD

**Issue by cci-nithin** [crossplane-contrib/provider-upjet-aws#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

apigateway.aws.upbound.io

### Steps to Reproduce

Using.GitHub as our source of truth and ArgoCD to deploy Upbound manifest.

apiVersion: apigateway.aws.upbound.io/v1beta1
kind: RestAPI
metadata:
  labels:
    apigateway.upbound.io/ext-name: exampleapi
  name: exampleapi
spec:
  forProvider:
    description: This is my Example API for demonstration purposes
    name: exampleapi
    region: eu-west-1

---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Resource
metadata:
  labels:
    apigateway.upbound.io/ext-name: exampleapi
  name: exampleresource
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        apigateway.upbound.io/ext-name: exampleapi
    pathPart: api
    region: eu-west-1
    restApiIdSelector:
      matchLabels:
        apigateway.upbound.io/ext-name: exampleapi

---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Deployment
metadata:
  labels:
    apigateway.upbound.io/ext-name: exampleapi
  name: stage
spec:
  forProvider:
    region: eu-west-1
    restApiIdSelector:
      matchLabels:
        apigateway.upbound.io/ext-name: exampleapi

---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Stage
metadata:
  labels:
    apigateway.upbound.io/ext-name: exampleapi
  name: exampleapi
spec:
  forProvider:
    deploymentIdSelector:
      matchLabels:
        apigateway.upbound.io/ext-name: exampleapi
    region: eu-west-1
    restApiIdSelector:
      matchLabels:
        apigateway.upbound.io/ext-name: exampleapi
    stageName: testing

### What happened?

Hi Team,

Created ApiGateway with Resources, Methods and deployed the stack which works great. However, if I update my stack (with a change in the Method or Resource), the API does not get deployed again. If I manually deploy the stack ArgoCD is reverting back to previous version. 

Anyone now how I can automatically deploy the gateway when the stack is updated?

### Crossplane Version

1.12.3-up.1

### Provider Version

v0.38.0

### Kubernetes Version

1.26

### Kubernetes Distribution

EKS

**Comment by turkenf** [comment]
Hi @cci-nithin,

From the information you provided, I cannot understand the exact situation you want or the error you are getting. First, try it in the latest provider version and if the situation is still valid, could you please share the clear replication steps and error message or expected situation with us?

**Comment by cci-nithin** [comment]
Hi @turkenf 

We set up an API Gateway (RestAPI) using Argocd and the Upbound provider, configuring resources and methods. Following that, we defined a stage and deployed it using the Upbound manifest. In order to introduce new methods, it is required to redeploy the API Gateway (RestAPI). However, when attempting to redeploy the existing Upbound deployment manifest, a message indicates that it is already synchronized.

Is there a specific trigger or method to redeploy the existing manifest with a new version?

**Comment by gbvanrenswoude** [comment]
@cci-nithin Did you manage to solve this? And if yes, what has been your solution?

**Comment by cci-nithin** [comment]
@gbvanrenswoude  No its still an bug or issue

**Comment by gbvanrenswoude** [comment]
@cci-nithin Any workarounds you might have applied?
