### ISSUE TITLE
[Elasticache] - Allow option to autogenerate password for auth

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [crossplane-contrib/provider-upjet-aws#1102]
### What problem are you facing?

We are looking at migrating from the [community AWS provider](https://doc.crds.dev/github.com/crossplane/provider-aws/cache.aws.crossplane.io/ReplicationGroup/v1beta1@v0.46.0) to the upbound ones. One significant difference we see is that this provider strictly requires a secret being passed in for auth, whilst we can see the use for this it would also be good to have the ability to autogenerate the password as we currently do and send the result out to `writeConnectionSecretToRef` in a similar way to what happens when creating dynamodb tables using this provider. 

The reason we have this requirement is our infrastructure is entirely gitops based including the manifests used in crossplane so any situation where we have to provide passwords means entering them into git which isn't ideal

### How could Official AWS Provider help solve your problem?
Without this migrating to the upbound provider is quite difficult if not potentially impossible (investigations still ongoing)

**Comment by turkenf** [comment]
Hi @dhumphries-sainsburys,

Thank you for raising this issue, if you would like to contribute we would appreciate it, here is a sample PR: https://github.com/upbound/provider-aws/pull/628

**Comment by WolfGanGeRTech** [comment]
Having the same issue, really tricky to migrate the provider for elastic cache. @dhumphries-sainsburys even with this feature I am not sure how it is possible to recreate the secret with the password in there, I guess it is not possible.
