### ISSUE TITLE
[Opensearch] Implement better subnet discovery - subnetIdSelector? 

### ISSUE THREAD

**Issue by billabongrob** [crossplane-contrib/provider-upjet-aws#1112]
### What problem are you facing?

The crossplane-contrib aws provider leveraged `subnetIdSelector` in the following file:  https://github.com/crossplane-contrib/provider-aws/blob/713458364ba9d9c7c5dfe94c47b12fc3ceb959ef/apis/opensearchservice/v1alpha1/custom_types.go 

It doesn't appear that this is available in the current version of Opensearch provider.  

### How could Official AWS Provider help solve your problem?

We should add this functionality back to the provider, unless there is a more preferred method of subnet discovery that is preferred over this one.

**Comment by haarchri** [comment]
for all inputs in https://marketplace.upbound.io/providers/upbound/provider-aws-opensearch/v0.47.1/resources/opensearch.aws.upbound.io/Domain/v1beta1#doc:spec-forProvider-vpcOptions the reference / selector is missing
