### ISSUE TITLE
Request for `ServerlessCache` resource

### ISSUE THREAD

**Issue by phyrog** [crossplane-contrib/provider-upjet-aws#1117]
### What resource do you need?

Terraform Resource Name:

- [aws_elasticache_serverless_cache](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache)

Available in AWS Terraform provider 5.32.0.

### What is your use case?

Deploy a serverless elasticache/redis cluster.

**Comment by turkenf** [comment]
Hi @phyrog,

Thank you for raising this request. Currently, we are using terraform version [5.31.0](https://github.com/upbound/provider-aws/blob/8d879bc3b73b8ea665709eba467d438ab841b62a/Makefile#L11C38-L11C44), we can add this resource after upgrading the version to 5.32.0 or later. This resource is a [framework resource](https://github.com/hashicorp/terraform-provider-aws/blob/870bdfa7945bc9c7deef4ebab553a335788c76ec/internal/service/elasticache/serverless_cache.go#L37).

**Comment by cawirawa** [comment]
Any updates on this?

**Comment by MichaelRSilva** [comment]
Any update about add this resource?
