### ISSUE TITLE
[Bug]: AWS API Gateway Provider Crashget

### ISSUE THREAD

**Issue by robpi** [crossplane-contrib/provider-upjet-aws#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

apigateway.aws.upbound.io/v1beta1 - all

### Resource MRs required to reproduce the bug

N/A -- This is just an install of the actual API Gateway Provider (v1), 0.47 worked fine.

### Steps to Reproduce

- Upgrade API Gateway provider to v1.0 from v0.47 on an EKS cluster. 

- Do a "k get providers" and it will initially show True/True for healthy/installed.
 
- Wait 5 minutes and check the providers again, api gateway will show True/False.
 
- If you check the pod for provider-aws-gateway it will show it in a CrashLoopBackOff state
 
- Check the logs and it will show json unmarshal errors

### What happened?

The pod is in a CrashLoopBackOff state instead of healthy

### Relevant Error Output Snippet

```shell
These two error messages repeatedly show up in the logs:

W0206 20:53:33.607808       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1beta1.RestAPI: json: cannot unmarshal number into Go struct field RestAPIParameters.items.spec.forProvider.minimumCompressionSize of type string

E0206 20:53:33.607843       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1beta1.RestAPI: failed to list *v1beta1.RestAPI: json: cannot unmarshal number into Go struct field RestAPIParameters.items.spec.forProvider.minimumCompressionSize of type string
```

### Crossplane Version

v1.14.5-up.1

### Provider Version

v1.0

### Kubernetes Version

1.28

### Kubernetes Distribution

EKS

**Comment by mbbush** [comment]
I was unable to reproduce this with the steps provided. 

Given that provider version 1.0.0 changed the type of spec.forProvider.minimumCompressionSize from `number` to `string`, this sure looks like it's somehow related to the conversion webhooks. I suspect it will be necessary to have a `v1beta` RestApi present in the cluster, which sets a number value for `spec.forProvider.minimumCompressionSize`, before doing the upgrade, in order to reproduce this bug, but I have not tried this yet.

**Comment by cci-nithin** [comment]
Same issue. 

`W0219 10:21:04.181515       1 reflector.go:539] k8s.io/client-go@v0.29.1/tools/cache/reflector.go:229: failed to list *v1beta1.RestAPI: json: cannot unmarshal number into Go struct field RestAPIParameters.items.spec.forProvider.minimumCompressionSize of type string
E0219 10:21:04.181563       1 reflector.go:147] k8s.io/client-go@v0.29.1/tools/cache/reflector.go:229: Failed to watch *v1beta1.RestAPI: failed to list *v1beta1.RestAPI: json: cannot unmarshal number into Go struct field RestAPIParameters.items.spec.forProvider.minimumCompressionSize of type string`
