### ISSUE TITLE
Request for `aws_msk_vpc_connection` resource

### ISSUE THREAD

**Issue by Brightside56** [crossplane-contrib/provider-upjet-aws#1145]
### What resource do you need?

**Terraform Resource Name:** 
aws_msk_vpc_connection

### What is your use case?
Expose MSK endpoints to another VPCs and put MSK brokers behind loadbalancer with static fqdn

**Comment by turkenf** [comment]
@Brightside56, thank you for raising this.

We would be happy if you would like to contribute, [this guide](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-short.md) may be useful to you. If you encounter any problems, don't hesitate to reach out.
