### ISSUE TITLE
Request for MemoryDB User resource

### ISSUE THREAD

**Issue by rainfollower** [crossplane-contrib/provider-upjet-aws#1149]
### What resource do you need?

Terraform Resource Name:

aws_memorydb_user

### What is your use case?

Provide management of MemoryDB users within provider-aws-memorydb. The provider includes an MR for managing MemoryDB Access Control Lists, but no MR for managing the users specified within the ACL.

**Comment by turkenf** [comment]
Related https://github.com/upbound/provider-aws/issues/368
