### ISSUE TITLE
Unable to import an AWS bucket notification into Crossplane 

### ISSUE THREAD

**Issue by giulio-chillipharm** [crossplane-contrib/provider-upjet-aws#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* s3.aws.upbound.io/v1beta1 - BucketNotification

### Resource MRs required to reproduce the bug

`apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
name: my-imported-s3-bucket
annotations:
crossplane.io/external-name: test-bucket-sns-notification
spec:
managementPolicies: ["Observe"]
forProvider:
region: "eu-west-1"

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketNotification
metadata:
name: photo-upload
annotations:
crossplane.io/external-name: photo-upload
spec:
managementPolicies: ["Observe"]
forProvider:
region: eu-west-1
bucket: test-bucket-sns-notification
topic:
- topicArn: "arn:aws:sns:eu-west-1:xxxxxxxxxxxx:test-topic"`

### Steps to Reproduce

I manually created an S3 bucket and configured the bucket notification and SNS topic in the AWS console and then applied the manifest above to import the S3 bucket and bucket notification.

### What happened?

While the S3 bucket import was successful, the bucket notification import failed with the error below:
`Warning  CannotObserveExternalResource  2m25s (x52 over 53m)  managed/s3.aws.upbound.io/v1beta1, kind=bucketnotification  (combined from similar events): failed to observe the resource: [{0 reading S3 Bucket Notification (photo-upload): operation error S3: GetBucketNotificationConfiguration, https response error StatusCode: 301, RequestID: 1JT115BZP0EY2RZW, HostID: 4oqvs+uhxBPLenYw0DqOnsImZbfX9dfkwLN5EVAwHuylVIQhL4C9MrpI2OkDosCB0oiOCChYHaU=, api error PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.  []}]`

I can create a new bucket notification with Crossplane, but this replaces the existing one, hence I aim to import the existing one into Crossplane and then modify it as needed. According to [this](https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/) page of your documentation, it should be possible.

<img width="1214" alt="Screenshot 2024-02-27 at 10 20 40" src="https://github.com/upbound/provider-aws/assets/156785373/94a879db-2e47-43a3-b1c6-e0409bbde1fd">

### Relevant Error Output Snippet

```shell
Warning  CannotObserveExternalResource  2m25s (x52 over 53m)  managed/s3.aws.upbound.io/v1beta1, kind=bucketnotification  (combined from similar events): failed to observe the resource: [{0 reading S3 Bucket Notification (photo-upload): operation error S3: GetBucketNotificationConfiguration, https response error StatusCode: 301, RequestID: 1JT115BZP0EY2RZW, HostID: 4oqvs+uhxBPLenYw0DqOnsImZbfX9dfkwLN5EVAwHuylVIQhL4C9MrpI2OkDosCB0oiOCChYHaU=, api error PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.  []}]
```

### Crossplane Version

1.15.0

### Provider Version

1.1.0

### Kubernetes Version

1.27.3

### Kubernetes Distribution

EKS and Kind

### Additional Info

The region of the existing S3 bucket is correct and matches that of the configuration.

**Comment by mbbush** [comment]
This seems to work for me, but the external name of the bucket notification resource needs to be set to the name of the s3 bucket.
