### ISSUE TITLE
Lambda inline code

### ISSUE THREAD

**Issue by amihaylov** [crossplane-contrib/provider-upjet-aws#1198]
### What problem are you facing?
Currently there is no way to specify inline code like in cloud formation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#aws-properties-lambda-function-code--examples

It would be very useful for small lambda's that dont need to be packed (e.g. depend only on aws-sdk) and no complex deployment is needed.

### How could Official AWS Provider help solve your problem?

Implement lambda inline code.

**Comment by mbbush** [comment]
Is it possible to do this in terraform-provider-aws? This project uses that one as an intermediary, so until/unless it's offered in that provider, it would be difficult to implement here.
