### ISSUE TITLE
[Bug]: Cannot create aws ManagedPrefixList

### ISSUE THREAD

**Issue by jorgelon** [crossplane-contrib/provider-upjet-aws#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io/v1beta1
ManagedPrefixList

### Resource MRs required to reproduce the bug

mylist.yaml
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: ManagedPrefixList
metadata:
  name: whatever
spec:
...
```
```
resources:
  - mylist.yaml
```

### Steps to Reproduce

kubectl kustomize .
kustomize build .
or argocd sync operation

### What happened?

When argocd/kubectl kustomize / kustomize reads the kustomization file, they do not get any resources there.
The reason is related because the kind ends with "List" word. If I change the kind ManagedPrefixList and use ManagedPrefixLisX (for example) it reads and gets a resource

As I can read here 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds
#The name of a list kind must end with "List". Lists have a limited set of common metadata. All lists use the required "items" field to contain the array of objects they return. Any kind that has the "items" field must be a list kind.

But I suppose this is not a kubernetes list, right?

### Crossplane Version

1.15.2

### Provider Version

v1.2.0

### Kubernetes Version

1.29

### Kubernetes Distribution

kubeadm

**Comment by jorgelon** [comment]
Ok, maybe i must create a ManagedPrefixList as a list with ManagedPrefixListEntry as items, right?

**Comment by jorgelon** [comment]
Nah, it does not work
Here is the problem
https://github.com/kubernetes-sigs/kustomize/issues/5042

**Comment by vibe** [comment]
Have encountered this problem in the past, like you point out it is specific to the kustomize project, either you must apply it outside of kustomize, or apply it directly `kubectl apply -f .` 

With previous conversations with the crossplane team, the suggestion is of course to use crossplane tooling to deploy managed resources.

**Comment by jorgelon** [comment]
what tools they have?
