### ISSUE TITLE
Remove provider-aws-opsworks once its EOL is complete in May 2024

### ISSUE THREAD

**Issue by mbbush** [crossplane-contrib/provider-upjet-aws#1224]
AWS Opsworks is closed to new customers, and scheduled to become unavailable to all existing customers in the next few months. This means we can remove it from provider-aws, to slightly reduce the size, maintenance, and testing burdens of the provider. 

We should wait until AWS has actually completed their shutdown, as they have extended these types of EOL dates in the past.

Currently, the shutdown schedule is [March 31, 2024 for Puppet](https://docs.aws.amazon.com/opsworks/latest/userguide/opspup-eol-faqs.html), [May 5, 2024 for Chef](https://docs.aws.amazon.com/opsworks/latest/userguide/opscm-eol-faqs.html), and [May 26, 2024 for stacks](https://docs.aws.amazon.com/opsworks/latest/userguide/stacks-eol-faqs.html).

I've never used this service myself, so I don't actually know which managed resources are used for puppet vs chef vs stacks. I'm inclined to wait until all three are shut down, then remove the provider entirely. 

Note that we can also remove the opsworks exception from the `RegionAddition` override. 

Given that the service will no longer exist, although technically its removal would be a breaking change, I'm inclined to release the removal in a normal minor version bump. If there are good reasons not to do so (or reasons to not remove them at all), I'd be happy to hear them.

These resources were originally added in PR #444 (issue #313) . I'm curious if anyone involved in adding them knows if they were specifically requested, or merely added as part of systematically going through all the terraform-provider-aws resources to get broad crossplane support.

**Comment by jeanduplessis** [comment]
@mbbush these were added as part of our expansion of resources effort. I'm not aware of anyone specifically asking for them.

I would not be against us removing the resources.
