### ISSUE TITLE
EFS FileSystem Support Of Lifecycle Policies - Transition to Archive

### ISSUE THREAD

**Issue by jacob-kuder** [crossplane-contrib/provider-upjet-aws#1243]
### What problem are you facing?

The AWS EFS provider does not allow you to configure archive lifecycle policies for EFS file systems.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-efs-filesystem-lifecyclepolicy.html
![image](https://github.com/crossplane-contrib/provider-upjet-aws/assets/110561326/61dca100-da7a-4cdc-bf9d-d3e8b3788e3d)

### How could Official AWS Provider help solve your problem?

Update the existing EFS FileSystem to support this feature so we can easily transition EFS to Archive storage.
https://marketplace.upbound.io/providers/upbound/provider-aws-efs/v1.2.1/resources/efs.aws.upbound.io/FileSystem/v1beta1

**Comment by turkenf** [comment]
Hi @jacob-kuder,

Could you give more information about what kind of support you would like and which fields you would like to be added? Are these fields available in the underlying terraform provider?

**Comment by jacob-kuder** [comment]
Hey @turkenf,

So, Terraform itself offers the transition to Archive functionality, shown here in their docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#lifecycle_policy-block

We are requesting similar functionality in the EFS provider...maybe something like `transitionToArchive` or similar. We'd like to see this added to the AWS EFS provider instead of through the Terraform provider.

**Comment by turkenf** [comment]
Thank you for your quick response, @jacob-kuder. This field was introduced in a newer version ([5.32.0](https://registry.terraform.io/providers/hashicorp/aws/5.32.0/docs/resources/efs_file_system#transition_to_archive)) than the version ([5.31.0](https://github.com/crossplane-contrib/provider-upjet-aws/blob/632aa6df85468904b694880811ffa0c88592801b/Makefile#L14)) we currently use.

When we upgrade the underlying provider, the field will be available.
