### ISSUE TITLE
[Bug]: EKS ClusterAuth v1.3.0 kubeconfig results in Unauthorized

### ISSUE THREAD

**Issue by lajchon** [crossplane-contrib/provider-upjet-aws#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps to Reproduce

After creating EKS `Cluster`, create `ClusterAuth` with `writeConnectionSecretToRef` configured. Create provider-kubernetes ProviderConfig to reference `ClusterAuth` Secret, or retrieve `kubeconfig` from Secret to use manually. `ProviderConfig` configured with IRSA `credentials.source` and `assumeRoleChain`.

### What happened?

When utilizing provider-aws-eks `v1.3.0`, usage of the `kubeconfig` results in `cannot get object: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/v1: Unauthorized`. 

Downgrade to provider-aws-eks `v1.2.0`, and `kubeconfig` is updated and access to the EKS cluster is available.

The same results are exhibited when accessing an EKS cluster provisioned with `v1.2.0`, which worked as expected, but after upgrading to `v1.3.0`, the `Unauthorized` error began.

### Crossplane Version

1.15.1

### Provider Version

1.3.0

### Kubernetes Version

v1.29.2

### Kubernetes Distribution

EKS

**Comment by adamhouse** [comment]
Some additional information- on the cluster side, we see the authenticator is logging the following on repeat:

```json
{
  "Error": {
    "Code": "SignatureDoesNotMatch",
    "Message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.",
    "Type": "Sender"
  },
  "RequestId": "171b39d0-6bd1-4c09-97eb-1e3ee7f23098"
}
```

**Comment by haarchri** [comment]
could be related to https://github.com/aws/aws-sdk-go-v2/issues/2567

**Comment by elihuj117** [comment]
I am seeing this with v1.15.0 of the provider as well. When I decode the token, I see the following:

`https://sts.us-east-1.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241015T195616Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host%3Bx-k8s-aws-id&X-Amz-Signature=REDACTED: invalid input`

Visiting the URL, I see: 
```
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
<Error>
<Type>Sender</Type>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>
</Error>
<RequestId>e297f116-de2a-40ca-941a-74ddb40bf175</RequestId>
</ErrorResponse>
```
