### ISSUE TITLE
AWS Redshift Cluster - Add support for MultiAZ

### ISSUE THREAD

**Issue by MattLamont** [crossplane-contrib/provider-upjet-aws#1255]
### What problem are you facing?

The `Cluster.redshift.aws.upbound.io/v1beta1` resources is missing field `multiAZ`:

```
MultiAZ
    If true, Amazon Redshift will deploy the cluster in two Availability Zones (AZ).
    Type: Boolean
    Required: No
```

Without this field, Redshift clusters always default to single AZ and all nodes are deployed to the same AZ.

We would like to deploy AWS Redshift clusters with multiple nodes spread across different availability zones for high availability using the MultiAZ attribute.

### How could Official AWS Provider help solve your problem?

Add the `multiAZ` attribute to the `Cluster.redshift.aws.upbound.io/v1beta1` resource.

**Comment by turkenf** [comment]
Hi @MattLamont, thank you for bringing up this issue. This field was introduced in a newer version ([5.35.0](https://registry.terraform.io/providers/hashicorp/aws/5.35.0/docs/resources/redshift_cluster#multi_az)) than the version ([5.31.0](https://github.com/crossplane-contrib/provider-upjet-aws/blob/5b1f14b6090835a5f0d4677680c17b35bccfd1d6/Makefile#L14)) we currently use.

When we upgrade the underlying provider, the field will be available.
