### ISSUE TITLE
"allocationRefId" for LB in provider-aws-elbv2

### ISSUE THREAD

**Issue by milers0** [crossplane-contrib/provider-upjet-aws#1278]
### What problem are you facing?

It seems that the property "allocationRefId" has not been implemented for [LB in provider-aws-elbv2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-elbv2/v1.3.1/resources/elbv2.aws.upbound.io/LB/v1beta1#doc:spec-forProvider-subnetMapping-allocationId).

When creating an internet-facing load balancer, I would like to make a reference to a public IP address that is already created with Crossplane (using kind: EIP). In other providers/CRDs, such as [NATGateway in provider-aws-ec2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.3.1/resources/ec2.aws.upbound.io/NATGateway/v1beta1#doc:spec-forProvider-allocationIdRef), it is possible to use allocationIdRef to make a reference to the EIP object, to actually use the IP address, but LB only allows allocationId. Not having allocationIdRef requires a manual update by checking the allocationId in the AWS console.

### How could Official AWS Provider help solve your problem?

By implementing the "allocationRefId" property for [LB in provider-aws-elbv2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-elbv2/v1.3.1/resources/elbv2.aws.upbound.io/LB/v1beta1#doc:spec-forProvider-subnetMapping-allocationId). It has already been implemented by other providers, for example, [NATGateway in provider-aws-ec2 (v1.3.1)](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.3.1/resources/ec2.aws.upbound.io/NATGateway/v1beta1#doc:spec-forProvider-allocationIdRef).

Thank you for taking the time to read the issue. If I have overlooked anything, then please let me know.

P.S. This issue was first raised [here](https://github.com/crossplane/crossplane/issues/5617), but it was mentioned to open the issue here.

**Comment by mbbush** [comment]
It sounds like the request is to add a new cross-resource reference to this resource kind. 

This would be a great first contribution if you're willing. There are plenty of examples to follow and automated tests to run to ensure you're doing it correctly.

Basically all you'd need to do would be:
* Add another entry like https://github.com/crossplane-contrib/provider-upjet-aws/blob/920c193d22af33537bfdc1b004920470479a6197/config/elbv2/config.go#L24-L26 to declare that the `allocationId` property is a reference to an EIP object
* Run `make generate` (currently this takes 5-10 minutes to run, while producing no console output, so be patient)
* Update the example manifest for the elb to use the new field
* Either test the manifest locally or (get someone to help you) run the test on your PR.

**Comment by milers0** [comment]
Hi Matt, thanks for the explanation!

I will give it a go somewhere this or next week. At the moment, I do not have any experience with Go nor with Open Source projects. Hope that's okay!
