### ISSUE TITLE
Request for `ec2_client_vpn_*` resources

### ISSUE THREAD

**Issue by milers0** [crossplane-contrib/provider-upjet-aws#1279]
### What resource do you need?

Terraform Resource Name: 
- [ec2_client_vpn_authorization_rule](https://registry.terraform.io/providers/hashicorp/aws/5.46.0/docs/resources/ec2_client_vpn_authorization_rule)
- [ec2_client_vpn_endpoint](https://registry.terraform.io/providers/hashicorp/aws/5.46.0/docs/resources/ec2_client_vpn_endpoint)
- [ec2_client_vpn_network_association](https://registry.terraform.io/providers/hashicorp/aws/5.46.0/docs/resources/ec2_client_vpn_network_association)
- [ec2_client_vpn_route](https://registry.terraform.io/providers/hashicorp/aws/5.46.0/docs/resources/ec2_client_vpn_route)

### What is your use case?

I would like to create and manage the Client VPN provided by AWS. This would allow a connection to the private network in AWS from any location without having to manage your own VPN.

Thank you for taking the time to read the issue. If I have overlooked anything, then please let me know.

**Comment by turkenf** [comment]
Hi @milers0, thank you for bringing up this, we would appreciate it if you would like to contribute.

We have a guide on adding new resources [here](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-short.md), some parts may be out of date, if you have any questions feel free to ask.
