### ISSUE TITLE
Support EKS API Authentication Mode

### ISSUE THREAD

**Issue by linusyong** [crossplane-contrib/provider-upjet-aws#1296]
### What problem are you facing?
EKS cluster supports EKS API authentication mode as describe in https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html.  Discussed on Slack with @haarchri is that this is supported in newer TF provider version and a version bump needed to provide this capability.

### How could Official AWS Provider help solve your problem?
Supporting EKS API authentication mode allows better support rather than the old `aws-auth` `configMap` authentication.

**Comment by fernandezcuesta** [comment]
duplicates #1098

**Comment by danielloader** [comment]
This isn't a duplicate, this ticket is about using IAM pod identity controller to inject the correct credentials into the provider pod to use to manage resources.

The other issue is creation of an aws resource for adding access entries to the cluster.

**Comment by haarchri** [comment]
This is implemented and available in V1.10.0
