### ISSUE TITLE
[Question] How to configure a API Gateway v2 Stage name?

### ISSUE THREAD

**Issue by marmol-dev** [crossplane-contrib/provider-upjet-aws#1353]
### Versions:

crossplane: 1.15.2
crossplane-aws-apigatewayv2:  1.4.0

### Question:

How I configure a AWS API Gateway v2 Stage name?

I need to create a stage with the name $default to automatically deploy changes of my APIs. The AWS Stage name is the same that the "metadata.name" of the Stage resource and in the [documentation](https://marketplace.upbound.io/providers/upbound/provider-aws-apigatewayv2/v1.6.0/resources/apigatewayv2.aws.upbound.io/Stage/v1beta1#doc:spec-forProvider) there is no field for configuring this. In the API Gateway v1 there is a `stageName` field for this ([documentation](https://marketplace.upbound.io/providers/upbound/provider-aws-apigateway/v1.6.0/resources/apigateway.aws.upbound.io/Stage/v1beta1#doc:spec-forProvider-stageName)).

Thanks for the support.

**Comment by mbbush** [comment]
Set the desired name in `metadata.annotations[[crossplane.io/external-name](http://crossplane.io/external-name)]`

**Comment by marmol-dev** [comment]
thanks, that's exactly what I was looking for @mbbush
