### ISSUE TITLE
Add bootstrapSelfManagedAddons to Cluster EKS Provider spec

### ISSUE THREAD

**Issue by lajchon** [crossplane-contrib/provider-upjet-aws#1382]
### What problem are you facing?

Currently, EKS Cluster creation defaults to installing several components: CoreDNS, kube-proxy, and VPC CNI. Announced by Amazon yesterday, [here](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-eks-cluster-creation-flexibility-networking-add-ons/), a new CLI flag is available, `bootstrapSelfManagedAddons`, to disable the automatic deployment of these components.

[Creating an Amazon EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html)

By default, EKS installs multiple networking add-ons during cluster creation. This includes the Amazon VPC CNI, CoreDNS, and kube-proxy.

If you'd like to disable the installation of these default networking add-ons, use the parameter below. This may be used for alternate CNIs, such as Cilium. Review the [EKS API reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html) for more information.

`aws eks create-cluster --bootstrapSelfManagedAddons false`

**Comment by haarchri** [comment]
we depend on the TF Provider: https://github.com/hashicorp/terraform-provider-aws/issues/38156 and this open PR here: https://github.com/hashicorp/terraform-provider-aws/pull/38162

**Comment by mithie** [comment]
Great that Amazon addresses this! This would be a high priority issue for us since we currently have to work with all kinds of workarounds in order to get rid of the Amazon VPC CNI and reinstall a new CNI afterwards.

**Comment by mergenci** [comment]
Looks like [`bootstrapSelfManagedAddons` attribute](https://github.com/crossplane-contrib/provider-upjet-aws/blame/c0d71c5f67cd18f80982aa246f9d10e3b5f3020d/apis/eks/v1beta2/zz_cluster_types.go#L63) was introduced with the [Terraform provider v5.58.0 version bump](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1406).
