### ISSUE TITLE
Request for feature to support docdb restore to point in time. 

### ISSUE THREAD

**Issue by confused-r-u** [crossplane-contrib/provider-upjet-aws#1393]
Currently I can provision docdb using upbound provider, but there is no option to `restore to point in time` using this provider.

Looks like tf provider has it already:

https://github.com/hashicorp/terraform-provider-aws/commit/b2fcf9599e4650f90e458968cae7cf72c8b16cd7

**Comment by jeanduplessis** [comment]
This functionality was introduced in version 5.57.0 of the Terraform provider.
Current we are consuming v5.50.0.
There are plans to update to the latest TF provider by the end of July at which point this would become available.

**Comment by confused-r-u** [comment]
Thank you!

**Comment by confused-r-u** [comment]
Will be added soon.
