### ISSUE TITLE
[Bug]: API Gateway Deployment: refuse to update the external resource because the following update requires replacing it

### ISSUE THREAD

**Issue by marmol-dev** [crossplane-contrib/provider-upjet-aws#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* deployment.apigateway.aws.upbound.io/v1beta1
* stage.apigateway.aws.upbound.io/v1beta1
* restapi.apigateway.aws.upbound.io/v1beta1

### Resource MRs required to reproduce the bug

```
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: RestAPI
metadata:
  labels:
    api: int-sandbox-dev-demo
  name: int-sandbox-dev-demo
spec:
  forProvider:
    body: >-
      ${jsonencode({
          openapi = "3.0.1"
          info = {
            title   = "demo"
            version = "1.0"
          }
          paths = {}
          
        })}
    name: int-sandbox-dev-demo
    region: eu-west-3
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: int-sandbox-dev-demo
  name: int-sandbox-dev-demo
spec:
  forProvider:
    region: eu-west-3
    restApiIdSelector:
      matchLabels:
        api: int-sandbox-dev-demo
    triggers:
      version: "1"
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Stage
metadata:
  labels:
    stage: int-sandbox-dev-demo
  name: int-sandbox-dev-demo
spec:
  forProvider:
    region: eu-west-3
    restApiIdSelector:
      matchLabels:
        api: int-sandbox-dev-demo
    stageName: int-sandbox-dev-demo
    deploymentIdSelector:
      matchLabels:
        deployment: int-sandbox-dev-demo
```

### Steps to Reproduce

1. Deploy the submited MRs: `kubectl apply resources.yaml`
2. Change the deployment trigger's field: `version: "2"`
3. Deploy the MRs: 'kubectl apply resources.yaml`

### What happened?

The Deployment MR is expected to reconcile with AWS but a error is obtained: `refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "triggers.version" from "1" to "2"`

I expect that the trigger property of the Deployment MR works exactly doing this: force a replacement of the underlying Terraform and AWS resource.

### Relevant Error Output Snippet

```shell
Conditions:
    Last Transition Time:  2024-08-01T08:55:43Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-08-01T08:56:16Z
    Message:               update failed: async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "triggers.version" from "1" to "2"
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
    Last Transition Time:  2024-08-01T08:56:16Z
    Message:               async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "triggers.version" from "1" to "2"
    Reason:                AsyncUpdateFailure
    Status:                False 
    Type:                  LastAsyncOperation
Events:
  Type     Reason                        Age               From                                                        Message
  ----     ------                        ----              ----                                                        -------
  Normal   CreatedExternalResource       43s               managed/apigateway.aws.upbound.io/v1beta1, kind=deployment  Successfully requested creation of external resource
  Normal   UpdatedExternalResource       9s                managed/apigateway.aws.upbound.io/v1beta1, kind=deployment  Successfully requested update of external resource
  Warning  CannotUpdateExternalResource  2s (x10 over 9s)  managed/apigateway.aws.upbound.io/v1beta1, kind=deployment  async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "triggers.version" from "1" to "2"
```

### Crossplane Version

1.16.0

### Provider Version

1.9.0

### Kubernetes Version

v1.30.2-eks-db838b0

### Kubernetes Distribution

EKS

### Additional Info

The reason I use "triggers" is to create a new Deployment on AWS with the changes of the RestAPI resource. I want to simulate the "Deploy" button on the AWS console.

**Comment by blakeromano** [comment]
I don't think this is a bug from what I understand...

Crossplane Providers will not update a resource if it requires a re-creation (or at least in my experience upjet ones do not for sure). I think you'd have to create a new resource, then delete this resource (or however TF deals with replacements of this resource assuming you feel that makes sense).

**Comment by marmol-dev** [comment]
Thanks @blakeromano , I understand the challenge for Crossplane with recreation.

But, what is the purpose of the "triggers" attribute of "deployment.apigateway.aws.upbound.io/v1beta1" ? It will always force recreation.

**Comment by blakeromano** [comment]
I am not an API Gateway expert by assumption is a deployment is essentially "immutable" where once you create a deployment your path forward is to create a new deployment not update existing. Upjet providers use Terraform under the hood with some customizations to make it K8s native so there's other resources which are pretty "immutable" that you can deploy with Crossplane.

**Comment by gbvanrenswoude** [comment]
@marmol-dev Did you manage to solve this? And if yes, what has been your solution?

**Comment by cjuega** [comment]
This should be reopened... current behavior makes the use of `triggers` useless. Even worse, using `triggers` will lead to **unready** resources. Not to say that current behavior means this provider doesn't behave as the terraform module it's built from.

@jeanduplessis, this ticket should be treated as https://github.com/crossplane-contrib/provider-upjet-aws/issues/1813. Even though the root cause is different, the user experience is the same in both cases.

For anybody coming to this in the future, there is a workaround, although it's not very performant. You can tag the Deployment with `deletionPolicy: Orphan` and make sure you put whatever criteria you wanted in triggers, in the `metadata.name`. That will make sure a new Deployment is created whenever the name changes, i.e. following your bump criteria. The drawback? Crossplane will probably create multiple Deployments when you only wanted one.

Here is a working example using KCL:

```
observedResources = [item?.Resource for _, item in option("params").ocds if item?.Resource?.kind != "Deployment"]
observedResourcesIds = [resource?.status?.atProvider?.id for resource in observedResources]
versionHash = crypto.sha1(json.encode(observedResourcesIds))

{
    apiVersion = "apigateway.aws.upbound.io/v1beta1"
    kind = "Deployment"
    metadata = {
        labels = {
            "resource-name" = "${openapi.info.title}-${openapi.info.version}-${versionHash}".replace(" ", "-").lower()
        }
        name = "${openapi.info.title}-${openapi.info.version}".replace(" ", "-").lower()
    }
    spec = {
        deletionPolicy = "Orphan"
        forProvider = {
            region = <a region>
            restApiId = <a rest api id>
            stageName = <an stage name>
            description = "Deployment of ${openapi.info.title} ${openapi.info.version} on ${cfg.restApiStageName} stage"
        }
    }
}
```
