### ISSUE TITLE
ElastiCache Clusters write endpoint to secret

### ISSUE THREAD

**Issue by fortra-cloudops-platform** [crossplane-contrib/provider-upjet-aws#1458]
### What problem are you facing?

I need to support my companies declarative processes by reading the connection info from a ConfigMap/Secret.

### How could Official AWS Provider help solve your problem?

Follow standard practice with other resources by writing connection info (endpoint URL) to the secret created by `writeConnectionSecretToRef`

Provide as key/values in the Secret:
- endpoint_address
- endpoint_port

**Comment by aiell0** [comment]
The following PR implemented part of this (endpoint) for memcached only as redis is not supported in the Terraform schema as of yet: https://github.com/crossplane-contrib/provider-upjet-aws/pull/1440

I can include the port as well in a separate PR. If you are using Redis, I am afraid until Terraform itself is updated we won't have that just yet.

**Comment by aiell0** [comment]
@fortra-cloudops-platform I have created a [PR](https://github.com/hashicorp/terraform-provider-aws/issues/20394) in Hashicorp for Redis support here, unfortunately it is low priority so if you could give a thumbs up on it, it would help greatly.
