### ISSUE TITLE
[Bug]: RDS Instance 'identifier' cannot be set

### ISSUE THREAD

**Issue by moksongmin** [crossplane-contrib/provider-upjet-aws#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

`rds.aws.upbound.io/v1beta2` - Instance

### Resource MRs required to reproduce the bug

      - nameMetadata: "cmp-test-rds"
        deletionPolicy: "Orphan"
        providerConfigRef: "aws-provider-upbound-cmp-dev"
        allocatedStorage: "20"
        autoGeneratePassword: true 
        autoMinorVersionUpgrade: true
        backupRetentionPeriod: "3"
        backupWindow: "04:00-05:00"
        engine: "postgres"
        engineVersion: "16.1"
        identifier: "cmp-test-rds"
        instanceClass: "db.t3.micro"
        maintenanceWindow: "sun:00:00-sun:02:00"
        name: "TestDB"
        passwordSecretRef:
          key: "xyz"
          name: "xyz"
          namespace: "crossplane"
        publiclyAccessible: false
        region: *region
        skipFinalSnapshot: false
        finalSnapshotIdentifier: "final_snapshot"
        storageEncrypted: true
        storageType: "gp2"
        multiAz: true
        username: "adminuser"
        deletionProtection: true
        dbSubnetGroupNameSelector:
          matchLabels:
            db: cmp-dev-rds-integration-service
        vpcSecurityGroupIdSelector:
          matchLabels:
            csg: cmp-db-sg
            createdByCrossplane: "true"
            prefixName: *prefix
        tags:
          Name: "cmp-test-rds"

### Steps to Reproduce

I've updated the provided manifest and the template we use with the '`identifier`' specification, but ArgoCD is not able to sync and apply the `'identifier'`.  

### What happened?

The newly created RDS instance is created with `'terraform-20240816071534381600000036'` 'DB Identifier':
![image](https://github.com/user-attachments/assets/f1758b4d-46da-4213-a309-6f2620857015)

ArgoCD is not able to sync the identifier:
![image](https://github.com/user-attachments/assets/9d62bca7-2fcb-4438-8653-c9ceef1a1d71)

In the CRD, the `'identifier'` is visible only under `kubectl.kubernetes.io/last-applied-configuration` annotation, but it's not shown under the `spec` section.

### Crossplane Version

1.14.2

### Provider Version

1.0.0

### Kubernetes Version

1.29

### Kubernetes Distribution

EKS

**Comment by emily-zall** [comment]
in 1.15.0 I see identifier in the spec but it is still not reflected in the database identifer which is 'terraform-<timestamp>
