### ISSUE TITLE
Update the RDS provider documentation to specify that the username field is mandatory for defining the username of the master DB user.

### ISSUE THREAD

**Issue by thiagoscodelerae** [crossplane-contrib/provider-upjet-aws#1498]
The `username` field is not specified as required for DB instance creation on RDS provider documentation.
The documentation should be updated to specify this field as required.

Also, using the default value "postgres" would be good to implement if we don't set any value. (This is what AWS does on the Console as the default username option).

Affected Resource(s)
rds.aws.upbound.io/v1beta2 - Instance
https://marketplace.upbound.io/providers/upbound/provider-aws-rds/v1.12.0/resources/rds.aws.upbound.io/Instance/v1beta2

Source of this request: https://github.com/crossplane-contrib/provider-upjet-aws/issues/1476

**Comment by mergenci** [comment]
[Terraform documentation of the field](https://registry.terraform.io/providers/hashicorp/aws/5.58.0/docs/resources/db_instance#username) states “Required unless a `snapshot_identifier` or `replicate_source_db` is provided”. Attributes of complex resources cannot be classified into a binary “required” or not. As suggested, Upjet should better include such caveats in the documentation.

**Comment by mergenci** [comment]
Closing in favor of https://github.com/crossplane/upjet/issues/457.
