### ISSUE TITLE
VPC Lattice Service

### ISSUE THREAD

**Issue by okwilkins** [crossplane-contrib/provider-upjet-aws#1512]
### What problem are you facing?

I am attempting to implement a [Kubernetes API Gateway](https://kubernetes.io/docs/concepts/services-networking/gateway/) via the [aws-application-networking-k8s](https://github.com/aws/aws-application-networking-k8s) controller. This uses VPC lattices in its implementation.

### What could help solve your problem?

It seems like [Terraform has an implementation](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/vpclattice_service), so I am assuming it can be plugged into the relevant provider?

**Comment by mergenci** [comment]
Unfortunately no, not in provider-upjet-aws. The resource you linked to is in terraform-provider-awscc, which is different than terraform-provider-aws. In order to support the resource, one should create a new Crossplane Upjet provider, based on terraform-provider-awscc.
