### ISSUE TITLE
[Enhancement] Elasticache Valkey Support

### ISSUE THREAD

**Issue by aiell0** [crossplane-contrib/provider-upjet-aws#1522]
### What problem are you facing?

I would like to use the new Elasticache [Valkey](https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-elasticache-valkey/) service.

### What could help solve your problem?

Creating this just for record-keeping. [This](https://github.com/hashicorp/terraform-provider-aws/issues/39641) will need to be implemented first.

**Comment by stevendborrelli** [comment]
The upstream TF PR has been merged <https://github.com/hashicorp/terraform-provider-aws/pull/39745>

Expected to be part of the https://github.com/hashicorp/terraform-provider-aws/milestone/410 v5.73.0 coming out this week.

**Comment by jdelucaa** [comment]
Hey,

Is this out already?

**Comment by jeanduplessis** [comment]
AWS Terraform provider v5.73.0 was consumed in the [v1.17.0](https://github.com/crossplane-contrib/provider-upjet-aws/releases/tag/v1.17.0) release.

**Comment by karthikhirisavechandrashekar** [comment]
@jeanduplessis,
I am able to provision a valkey serverless cache using the v1.17.0 provider but it says it doesn't support provisioning a valkey cache cluster. Is this correct or am I missing something?
![image](https://github.com/user-attachments/assets/3a87223a-103d-416e-8a7a-a9a86cc90ccd)
