### ISSUE TITLE
Support RDS Global Database writer endpoint in "status"

### ISSUE THREAD

**Issue by ctenberge-oneid** [crossplane-contrib/provider-upjet-aws#1582]
### What problem are you facing?

The [GlobalCluster](https://marketplace.upbound.io/providers/upbound/provider-aws-rds/v1.17.0/resources/rds.aws.upbound.io/GlobalCluster/v1beta1) resource now has a "global writer endpoint" that is not available as a field in the "status" stanza. 

See Terraform attribute reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_global_cluster#endpoint-1

### What could help solve your problem?

Add a new field to the "status" stanza for "globalWriterEndpoint"

**Comment by mergenci** [comment]
This field is [supposed to](https://registry.terraform.io/providers/hashicorp/aws/5.78.0/docs/resources/rds_global_cluster#endpoint-5) arrive with our [work-in-progress Terraform provider v5.78.0 bump](https://github.com/crossplane-contrib/provider-upjet-aws/pull/1586). Can you please check if it exists? If so, there's nothing more to do than to wait for the next release.

**Comment by ctenberge-oneid** [comment]
The new release fixed this.
