### ISSUE TITLE
Add default_tags to ProviderConfig

### ISSUE THREAD

**Issue by mcanevet** [crossplane-contrib/provider-upjet-aws#169]
### What problem are you facing?

In the AWS Terraform provider, one can set [default tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) to apply to all resources managed by the provider. I'm wondering if we could also have this nice feature in Crossplane.

### How could Official AWS Provider help solve your problem?

Add `default_tags` property in `providerconfigs.aws.upbound.io`?

**Comment by nicraMarcin** [comment]
Hi,
are there any plans to add this?
