### ISSUE TITLE
Moving elasticache (2) resources to v1beta1 version

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-upjet-aws#252]
Moving 2 resources in the `elasticache` group:
- [ ] [`aws_elasticache_global_replication_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_global_replication_group)
- [x] [`aws_elasticache_user_group_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user_group_association)

**Comment by svscheg** [comment]
[aws_elasticache_user_group_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user_group_association): have an error for user creation:
- lastTransitionTime: "2022-12-14T21:15:17Z"
    message: 'cannot create or update connection secret: existing secret is not controlled
      by UID "0e3fa411-021e-4465-8179-7667a31e610d"'
could we manually create users and use in the test as id in UserGroup resource?

**Comment by svscheg** [comment]
aws_elasticache_global_replication_group
1. Primary replication group created successfully. But after creation GlobalReplicationGroup resource - I can see that [replicationgroup.elasticache.aws.upbound.io/primary](http://replicationgroup.elasticache.aws.upbound.io/primary) will have READY False, but it still READY True. 

Next attributes added to the IgnoredFields
: “parameter_group_name", "engine" but still have an error for the engine attribute

Error:     message: 'observe failed: cannot run refresh: refresh failed: Conflicting configuration
      arguments: "global_replication_group_id": conflicts with engine'


2. For second replication group (it depends from GlobalReplicationGroup) I have next error while creation(guess it's a connection problem not confirmed, run 3 times and have the same error):
- lastTransitionTime: "2022-12-26T18:02:18Z"
    message: 'observe failed: cannot run refresh: refresh failed: error configuring
      Terraform AWS Provider: error validating provider credentials: error calling
      sts:GetCallerIdentity: operation error STS: GetCallerIdentity, exceeded maximum
      number of attempts, 9, https response error StatusCode: 0, RequestID: , request
      send failed, Post "https://sts.us-west-1b.amazonaws.com/": dial tcp: lookup
      sts.us-west-1b.amazonaws.com on 127.0.0.2:53: no such host: '
