### ISSUE TITLE
Moving ecs (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-upjet-aws#255]
Moving 1 resource in the `ecs` group:
- [ ] [`aws_ecs_task_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_set)

**Comment by MyzaTaras** [comment]
Blocked due to the same problem with resource - [issues/28](https://github.com/upbound/provider-aws/issues/28)
