### ISSUE TITLE
provider-aws does not support source: Filesystem

### ISSUE THREAD

**Issue by celalettin1286** [crossplane-contrib/provider-upjet-aws#287]
### What problem are you facing?
I think below source code is already self explanatory.  Official AWS Provider doesn't support source: Filesystem and as seen in the below reference it checks for Secret, IRSA, WebIdentity.

https://github.com/upbound/provider-aws/blob/main/apis/v1beta1/types.go#L175

This is blocker for migrating from deprecated providers since we have implemented injecting cloud creds from vault using Filesystem.

**Comment by kkr2320** [comment]
Crossplane-Contrib provider support filesystem as source. I tested the latest release by adding Filesyatem as allowed source to the ProviderConfig CRD and it works . Is it bug that the CRD is not updated ?  
we use vault inject and feed credentials using side car.

**Comment by shuknk8s** [comment]
The issue with using crossplane-contrib provider is that down the line if you attempt to latest API spec for provisioning resources , the composition/XR request will fail complaining about kind missing, per my conversation with Chris Haar , the filesystem support in latest api of ProviderConfig should be updated. Waiting on @haarchri  to schedule the implementation
