### ISSUE TITLE
Moving macie (2) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane-contrib/provider-upjet-aws#301]
Moving 2 resources in the macie group:

- [ ] [aws_macie_member_account_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie_member_account_association)
- [ ] [aws_macie_s3_bucket_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie_s3_bucket_association)

**Comment by steperchuk** [comment]
macie classic deprecated according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie_member_account_association
https://docs.aws.amazon.com/general/latest/gr/macie.html
NOTE:
This resource interacts with [Amazon Macie Classic](https://docs.aws.amazon.com/macie/latest/userguide/what-is-macie.html). Macie Classic cannot be activated in new accounts. See the [FAQ](https://aws.amazon.com/macie/classic-faqs/) for more details.
It is not possible to verify resource with test accounts, as resource creation fails on 
"apply failed: Error creating Macie member account association: RequestError:
  send request failed\ncaused by: Post \"[https://macie.us-east-1.amazonaws.com/\":](https://macie.us-east-1.amazonaws.com//%22:)
 dial tcp: lookup macie.us-east-1.amazonaws.com on 8.8.8.8:53: no such host: "
