### ISSUE TITLE
Moving pinpoint (9) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane-contrib/provider-upjet-aws#315]
Moving 9 resources in the pinpoint group:

- [ ] [aws_pinpoint_adm_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_adm_channel)
- [ ] [aws_pinpoint_apns_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_channel)
- [ ] [aws_pinpoint_apns_sandbox_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_sandbox_channel)
- [ ] [aws_pinpoint_apns_voip_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_voip_channel)
- [ ] [aws_pinpoint_apns_voip_sandbox_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_voip_sandbox_channel)
- [ ] [aws_pinpoint_baidu_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_baidu_channel)
- [ ] [aws_pinpoint_email_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_email_channel)
- [ ] [aws_pinpoint_event_stream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream)
- [ ] [aws_pinpoint_gcm_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_gcm_channel)

**Comment by kdibrov** [comment]
1) aws_pinpoint_email_channel requires AWS SES service which is not yet configured 
2) all other resources require keys and/or secrets from AWS itself, Google or Apple. Needs investigation.
