### ISSUE TITLE
Moving storagegateway (10) resources to v1beta1 version

### ISSUE THREAD

**Issue by dverveiko** [crossplane-contrib/provider-upjet-aws#342]
Moving 10 resources in `storagegateway` group:

- [ ] [`aws_storagegateway_cache`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_cache)
- [ ] [`aws_storagegateway_cached_iscsi_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_cached_iscsi_volume)
- [ ] [`aws_storagegateway_file_system_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_file_system_association)
- [ ] [`aws_storagegateway_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_gateway)
- [ ] [`aws_storagegateway_nfs_file_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_nfs_file_share)
- [ ] [`aws_storagegateway_smb_file_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_smb_file_share)
- [ ] [`aws_storagegateway_stored_iscsi_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_stored_iscsi_volume)
- [ ] [`aws_storagegateway_tape_pool`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_tape_pool)
- [ ] [`aws_storagegateway_upload_buffer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_upload_buffer)
- [ ] [`aws_storagegateway_working_storage`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_working_storage)

**Comment by kdibrov** [comment]
Wasn't able to activate Storage Gateway. Attaching yaml file and conf file. 
[gateway.zip](https://github.com/upbound/provider-aws/files/10308184/gateway.zip)
