### ISSUE TITLE
Moving fsx (4) resources to v1beta1 version

### ISSUE THREAD

**Issue by svscheg** [crossplane-contrib/provider-upjet-aws#344]
Moving 4 resources in the fsx group:

- [ ] [aws_fsx_ontap_volume](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_volume)
- [ ] [aws_fsx_openzfs_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_file_system)
- [ ] [aws_fsx_openzfs_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_snapshot)
- [ ] [aws_fsx_openzfs_volume](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_volume)

Attached working yaml files:
[yaml files.zip](https://github.com/upbound/provider-aws/files/10279469/yaml.files.zip)

![Image](https://user-images.githubusercontent.com/114226153/210054775-b606469b-c80a-4b01-be4d-74947758ffd7.png)

**Comment by svscheg** [comment]
Need to investigate how to clear test env after the FSx deletion: main issue that after the successfully deletingtested resources we still have a backup for the ontap_file_system and for the openzfs_file_system.

Investigation details: tested FS have a default volume and while deleting the FS - backup created for default volumes, need to clear it manually.

Tested:
automaticBackupRetentionDays: 0 

Next step: try to set automaticBackupRetentionDays: 1 and wait 1 day to check if backup will be deleted

**Comment by svscheg** [comment]
[aws_fsx_openzfs_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_file_system)
 [aws_fsx_openzfs_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_snapshot)
For this 2 resources we will not have any backup - can merge it

**Comment by svscheg** [comment]
For resource [aws_fsx_openzfs_volume](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_volume) we will have backup for the volume, need post-delete hook

**Comment by colstrom** [comment]
Any chance that this could get reopened? This feature seems to be exactly what I'm looking for (specifically the `aws_fsx_openzfs_file_system` support), and that sounded like it was ready to merge, if I understand correctly?
