### ISSUE TITLE
Moving quicksight (2) resources to v1beta1 version

### ISSUE THREAD

**Issue by anastasiia-kvas** [crossplane-contrib/provider-upjet-aws#356]
Moving 2 resources in the quicksight group:

- [ ] [aws_quicksight_data_source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source)
- [ ] [aws_quicksight_group_membership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_group_membership)

Need more knowledge about config types in externalname.go.

**Comment by anastasiia-kvas** [comment]
Configurations that I've tried can be found in the file configurations.txt

[configurations.txt](https://github.com/upbound/provider-aws/files/10285611/configurations.txt)

**Comment by project-administrator** [comment]
Are there any plans to release this in the near future? 
Is there any porting guideline on how one can contribute to make this feature implemented?

**Comment by jeanduplessis** [comment]
@project-administrator, it is not a near-term focus, but we would be very happy to provide guidance and support if you are interested in contributing to it.

You can find the quick guide for adding resources here: https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md (there's also a more comprehensive one [here](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md))
