### ISSUE TITLE
Moving elasticbeanstalk(1) resources to v1beta1 version

### ISSUE THREAD

**Issue by anastasiia-kvas** [crossplane-contrib/provider-upjet-aws#357]
External name configuration of 1 resource in the `elasticbeanstalk` group:

* [`aws_elastic_beanstalk_environment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastic_beanstalk_environment)

` message: "apply failed: Error waiting for Elastic Beanstalk Environment (e-vu2pdgnm4z)
      to become ready: 2 errors occurred:\n\t* 2022-12-21 11:40:59.758 +0000 UTC (e-vu2pdgnm4z)
      : Environment must have instance profile associated with it.\n\t* 2022-12-21
      11:40:59.862 +0000 UTC (e-vu2pdgnm4z) : Failed to launch environment.\n\n: "`

Tried:

1. Adding separate Role and Instance Profiles into yaml
2. Adding Policy with permissions for everything
3. Changing solution stack name from Linux 2 to 64bit Windows Server Core 2019 v2.10.6 running IIS 10.0 (https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/iam-instanceprofile.html#:~:text=Create%20role.-,Instance%20profiles%20with%20Amazon%20Linux%202%20platforms,-Amazon%20Linux%202)
4. Adding [AWSElasticBeanstalkEnhancedHealth](https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth)  policy to aws-elasticbeanstalk-ec2-role (all Amazon Linux 2 platform versions enable enhanced health by default during environment creation.)

**Comment by MyzaTaras** [comment]
Removed `aws_elastic_beanstalk_application_version` - already tested.

**Comment by MyzaTaras** [comment]
Error appears during environment creation.
<img width="833" alt="Screenshot 2023-02-21 at 13 44 46" src="https://user-images.githubusercontent.com/119457707/220356069-2525a32e-c208-4afc-8653-da3946458d29.png">

<img width="1416" alt="Screenshot 2023-02-21 at 13 41 41" src="https://user-images.githubusercontent.com/119457707/220356118-db3d5450-1c4e-47eb-a58a-e662e926e3cc.png">

Environment name marked as terminated!
<img width="1398" alt="Screenshot 2023-02-21 at 13 41 56" src="https://user-images.githubusercontent.com/119457707/220356176-33535120-4260-4ddf-a308-9593100c533c.png">

Manual everything OK with the same parameters.
<img width="1262" alt="Screenshot 2023-02-21 at 13 49 57" src="https://user-images.githubusercontent.com/119457707/220356249-34dd17e6-b9bb-4243-b9d2-98806a9baabc.png">
