### ISSUE TITLE
Moving memorydb (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by svscheg** [crossplane-contrib/provider-upjet-aws#368]
Moving memorydb (1) resources to v1beta1 version

- [ ] [aws_memorydb_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_user)

Can be a bug:

message: 'observe failed: cannot run refresh: refresh failed: Missing required
      argument: The argument "passwords" is required, but no definition was found.'

[yaml_output.txt](https://github.com/upbound/provider-aws/files/10293299/yaml_output.txt)
[memorydb.aws.upbound.io_users.yaml.txt](https://github.com/upbound/provider-aws/files/10293308/memorydb.aws.upbound.io_users.yaml.txt)
[user.yaml.txt](https://github.com/upbound/provider-aws/files/10293307/user.yaml.txt)

**Comment by turkenf** [comment]
Covered with: https://github.com/crossplane-contrib/provider-upjet-aws/pull/1170
