### ISSUE TITLE
Moving wafregional(1) resource to v1beta1 version

### ISSUE THREAD

**Issue by dverveiko** [crossplane-contrib/provider-upjet-aws#412]
Moving `Wafregional ` 1 resource to v1beta1 version
- [ ] [aws_wafregional_web_acl_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_web_acl_association)

**Comment by kdibrov** [comment]
**Worklink** host is not being resolved in all regions:
"RequestError: send request failed\ncaused by: Post \"https://worklink.us-east-1.amazonaws.com/describeFleetMetadata\":
      dial tcp: lookup worklink.us-east-1.amazonaws.com on 127.0.0.1:53: no such host:"

**wafv2** web_acl fails to install crd with the following error:
`The CustomResourceDefinition "webacls.wafv2.aws.upbound.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
