### ISSUE TITLE
Missing selector in VPCEndpointService

### ISSUE THREAD

**Issue by ganeshk1928** [crossplane-contrib/provider-upjet-aws#425]
### What problem are you facing?

While trying to create a **VPCEndpointService** I'm unable to select **networkLoadBalancerArns** using labels. I can see that the label selector field is missing for this resource.

### How could Official AWS Provider help solve your problem?

Can you add the missing selector which will be something like **networkLoadBalancerARNSelector** to the **VPCEndpointService** resource. This is already available in the community contributed aws-provider. Please add it in the upbound provider as well.

**Comment by nabuskey** [comment]
I did some digging and ultimately ran into the cyclic import issue described [here](https://github.com/upbound/upjet/issues/96).  `ec2 --> lb --> ec2`

**Comment by turkenf** [comment]
- When we try to add a selector using `Terraform Name` or `Type` we get the following error:
<img width="1284" alt="Screenshot 2023-04-28 at 17 27 03" src="https://user-images.githubusercontent.com/103541666/235174911-2e88c884-1abf-4a20-bc50-1f3ef7948160.png">


- There is no solution to this issue for now. As mentioned above, there is an issue in `upjet` relevant to this. 
- Blocked by https://github.com/upbound/upjet/issues/96
