### ISSUE TITLE
Upbound AWS provider v 0.26.0 has vulnerabilites

### ISSUE THREAD

**Issue by dacoty** [crossplane-contrib/provider-upjet-aws#440]
The official AWS provider has some vulnerabilities(criticial/high) in the image that may need to be patched for the next release. screenshot taken from docker-desktop below. Looks like a lot of TF vulns. 
![image](https://user-images.githubusercontent.com/121582995/212128074-a7e23a33-ac1a-410e-b8ba-bfdb8f333ac2.png)

**Comment by svscheg** [comment]
Hi @dacoty ! 

The necessary configuration for Renovate has been added and seems this issue should be fixed. @dacoty could you please re-check it on the latest version of provider and we will close the issue if it is not relevant now.

**Comment by chlunde** [comment]
```
docker scout quickview xpkg.upbound.io/upbound/provider-aws:v1.5.0
    ✓ SBOM of image already cached, 362 packages indexed

  Target               │  xpkg.upbound.io/upbound/provider-aws:v1.5.0  │    0C     0H     5M     1L     2?
    digest             │  865d4c988b7d                                 │
  Base image           │  alpine:3                                     │    0C     0H     4M     0L     2?
  Refreshed base image │  alpine:3                                     │    0C     0H     0M     0L
                       │                                               │                  -4            -2
```

<img width="738" alt="image" src="https://github.com/crossplane-contrib/provider-upjet-aws/assets/131994/d9a73edd-a936-459e-b511-495621dfd003">

The AWS Go SDK issues have no fix except updating to SDK v2
