### ISSUE TITLE
ECS Provider refs and selectors that are missing

### ISSUE THREAD

**Issue by jpoley** [crossplane-contrib/provider-upjet-aws#467]
ECS Service and TaskDefinition has some places where using a Ref/Selector would make it easy use / reference the specific Arns 

### ECS Service 

**apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
spec.forProvider.loadBalacner[].targetGroupArn  #crossplane has it**

### ECS TaskDefinition

**apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskDefinition
spec.forProvider.executionRoleArn  #crossplane has it
spec.forProvider.taskRoleArn #crossplane has it**

The community provider has these specific Arn selectors, without them you can't seamlessly use ECS Fargate at all. (you would be forced to do cut and paste yaml after obtaining the appropriate ARNs.

**Comment by mhoshi-vm** [comment]
i think for ECS service was solved via #831
