### ISSUE TITLE
Error for some resources while make run

### ISSUE THREAD

**Issue by mykolalosev** [crossplane-contrib/provider-upjet-aws#515]
### What happened?
Will have error for the make run command after adding test resources:
 - [aws_appsync_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_type)
 
 The error:
```
... go generate linux_amd64
panic: cannot run goimports for internal folder: ./controller/zz_setup.go:109:1: expected 'STRING', found 'type'
./controller/zz_setup.go:821:2: expected 'STRING', found 'for'
./controller/zz_setup.go:914:3: expected 'STRING', found 'type'
./controller/zz_setup.go:1626:3: expected 'STRING', found 'if'
./controller/zz_setup.go:1627:4: expected 'STRING', found 'return'
./controller/zz_setup.go:1630:2: expected 'STRING', found 'return'
./controller/zz_setup.go:1631:3: expected ')', found 'EOF'
./controller/appsync/type/zz_controller.go:7:9: expected 'IDENT', found 'type'
./controller/appsync/type/zz_controller.go:9:1: expected ';', found 'import'
: exit status 2
```

### How can we reproduce it?

1. add resource to the config/externalname.go
2. make generate
3. apply crd
4. make run

### What environment did it happen in?

* Provider Name: provider-aws
* Provider Version: 4.52.0

**Comment by svscheg** [comment]
**Steps to reproduce:**

1. add resource to the config/externalname.go
3. make generate

**Expected result:**
make generate successful

**Actual result:**
Have next error:
go generate linux_amd64
panic: cannot run goimports for internal folder: ./controller/zz_setup.go:180:1: expected 'STRING', found 'type'
./controller/zz_setup.go:912:2: expected 'STRING', found 'for'
./controller/zz_setup.go:1005:3: expected 'STRING', found 'type'
./controller/zz_setup.go:1808:3: expected 'STRING', found 'if'
./controller/zz_setup.go:1809:4: expected 'STRING', found 'return'
./controller/zz_setup.go:1812:2: expected 'STRING', found 'return'
./controller/zz_setup.go:1813:3: expected ')', found 'EOF'
./controller/appsync/type/zz_controller.go:7:9: expected 'IDENT', found 'type'
./controller/appsync/type/zz_controller.go:9:1: expected ';', found 'import'
: exit status 2

The issue reproduced.
