### ISSUE TITLE
aws: "aws_s3_bucket_object_lock_configuration" resource configuration

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane-contrib/provider-upjet-aws#52]
### What problem are you facing?

When we try to create "aws_s3_bucket_object_lock_configuration" resource, it does not become ready due to the following error:
```
Warning  CannotCreateExternalResource  3s (x7 over 72s)     managed/s3.aws.upbound.io/v1beta1, kind=bucketobjectlockconfiguration  (combined from similar events): cannot apply: apply failed: error creating S3 bucket (ezgi-bucket) Object Lock configuration: InvalidBucketState: Object Lock configuration cannot be enabled on existing buckets
```
Provider Name: provider-aws

### How could Official Providers help solve your problem?

Creating a bucket and a lock configuration in the same Terraform workspace may work.

**Comment by brunogomes1** [comment]
maybe this helps you?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object_lock_configuration#object-lock-configuration-for-an-existing-bucket
