### ISSUE TITLE
EC2 Instance not getting created once terminated from AWS Console

### ISSUE THREAD

**Issue by saichaitanya11** [crossplane-contrib/provider-upjet-aws#602]
### What happened?

We have a cluster installed with Crossplane. An EC2 instance was created using Crossplane when the XRD, Composition and Claim were applied. Once the instance is terminated from AWS Console, a new instance is not being created again. Also, when the instance is stopped from AWS Console, the status of the instance is not changing to running state. Same behaviour is observed when EC2 instance was created using ArgoCD and Crossplane together. Please let us know if it is the expected behaviour or is it a bug.

### How can we reproduce it?

1. Create an EC2 instance using Crossplane.
2. Once the instance is ready, terminate the same in the AWS Console.
3. Observe the status of the EC2 instance.
4. Verify if the instance is being created again.

### What environment did it happen in?

* Universal Crossplane Version: v1.1.11
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.21.0
* OS: Linux
* Kubernetes Version: v1.24

**Comment by saichaitanya11** [comment]
Hello,

Can you please let me know if this issue will be fixed in the future as this has been a blocker for us. Also, if there is any way to resolve this from our end?

Thank you

**Comment by jeanduplessis** [comment]
@saichaitanya11 Is there a specific reason you need to use an old version of the was provider? The latest version is `xpkg.upbound.io/upbound/provider-aws:v0.31.0`. We'll look to replicate this issue, and if we can confirm the issue will put it on the team's backlog for fixing.

**Comment by robsclark** [comment]
I recommend upgrading to the latest version first @saichaitanya11

**Comment by saichaitanya11** [comment]
@jeanduplessis @robsclark Thank you for the response. We will try upgrading to the latest version and try again and then get back to you.

Thank you

**Comment by saichaitanya11** [comment]
Hello @jeanduplessis @robsclark ,

We tried upgrading to the latest version using the following command
kubectl patch provider.pkg "provider object name" -p '{"spec":{"package": "xpkg.upbound.io/upbound/provider-aws:v0.31.0"}}' --type=merge

Got the following result for _kubectl get providers_ command
NAME INSTALLED   *HEALTHY*   PACKAGE                                        AGE
provider-aws   True        *False*     xpkg.upbound.io/upbound/provider-aws:v0.31.0   47h

Please let us know how to resolve this issue. Due to this, unable to create any resources

Thank you

**Comment by svscheg** [comment]
Can reproduce behaviour on the latest version: xpkg.upbound.io/upbound/provider-aws:v0.31.0

**Comment by saichaitanya11** [comment]
Also, this issue is observed with the t2.micro instance type only. When the instance type was changed to t3.micro, instance is being created again after deleting.

**Comment by kaushik287** [comment]
The same issue has been observed for t2.small and t2.medium as well.
 Instances are not getting reconciled once terminated from AWS Console. This has been a blocker for us. Request to provide an update on this please. Thank you

**Comment by turkenf** [comment]
Hi folks,

For terminated cases: this behavior is expected, there is an issue in the `crossplane` repo related to this situation: https://github.com/crossplane/crossplane/issues/2704.

For stopped and running state cases: this behavior is also expected. Because there is a separate resource [ec2.InstanceState](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v0.36.0/resources/ec2.aws.upbound.io/InstanceState/v1beta1) to check this status, and I have verified that it works successfully.

Also, if you try to create the `ec2.Instance` resource with provider-aws v0.36.0, you will encounter a conflict error and please wait for this [PR](https://github.com/upbound/provider-aws/pull/749) that fixes it to merge.

**Comment by turkenf** [comment]
Blocked by https://github.com/crossplane/crossplane/issues/2704

**Comment by jeanduplessis** [comment]
Since the "terminated" resource exists in the AWS API, Crossplane behavior is as intended. 
The user should implement additional logic, possibly through Composition Functions, to manage the terminated state of the resource.
