### ISSUE TITLE
containerDefinitions in ECS TaskDefintion should be objects and not a string

### ISSUE THREAD

**Issue by martinflemingdev** [crossplane-contrib/provider-upjet-aws#625]
### What problem are you facing?
Currently the containerDefinitions array in the ECS TaskDefintion component takes a string representation of a JSON object.
This makes patching specific fields and verification very difficult.
Crossplane-contrib provider uses key:value objects instead.

![ECS-task-def-container](https://user-images.githubusercontent.com/78125388/227374734-b1bc8752-f749-411f-8603-6b7fe57e0f36.png)

### How could Official AWS Provider help solve your problem?
Please consider adopting the same approach as crossplane-contrib provider and provide Key:Value pairs instead of a string representation of a JSON object.

**Comment by jpoley** [comment]
This is blocking any use of patching, or real adoption
