### ISSUE TITLE
Request for `aws_lb_listener_certificate` resource

### ISSUE THREAD

**Issue by michaelvl** [crossplane-contrib/provider-upjet-aws#712]
### What resource do you need?

Terraform Resource Name: aws_lb_listener_certificate

### What is your use case?

This resource is needed to attach multiple certificates to a load balancer through an `LBListener` resource and is already mentioned in the documentation of the `certificateArn` of the `LBListener` resource: https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/elbv2.aws.upbound.io/LBListener/v1beta1

**Comment by turkenf** [comment]
Hi @michaelvl,

Thank you for raising this issue.
