### ISSUE TITLE
iam accesskey smtp password generation fails

### ISSUE THREAD

**Issue by alexinthesky** [crossplane-contrib/provider-upjet-aws#717]
### What happened?
smtp password is region specific so the region has to be specified in the provider block to be generated correctly by the TF see ->
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/iam/access_key.go#L125

this conflics with 
-> 
https://github.com/upbound/provider-aws/blob/main/config/overrides.go#L20

### How can we reproduce it?
try and use the smtp PWD generated for an ses server / accesskey in ap-southeast-1 region

### What environment did it happen in?

* Crossplane Version: 12
* Provider Version: 0.34.0

**Comment by turkenf** [comment]
PR opened by @alexinthesky: https://github.com/upbound/provider-aws/pull/718
