### ISSUE TITLE
route53 zone region required for global resource ?

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-upjet-aws#741]
### What happened?
any reason why region is required in official-provider-aws ? in my point of view route53 zone is global resource 
https://marketplace.upbound.io/providers/upbound/provider-aws-route53/v0.36.0/resources/route53.aws.upbound.io/Zone/v1beta1#doc:spec-forProvider-region

in community provider-aws we have no region field available
https://doc.crds.dev/github.com/crossplane-contrib/provider-aws/route53.aws.crossplane.io/HostedZone/v1alpha1@v0.40.0

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by svscheg** [comment]
Hi @haarchri !

The route53 zone is global resource, so we may consider removing the region field or converting the optional one but, this will be a breaking api change. 
So if current api does not affect the behaviour of this resource we can protect the current state.

The issue will be triaged and need more investigation to decide what actions we should to do in this situation.
