### ISSUE TITLE
TopicRule.iot.aws.upbound.io ignores changes to clientProperties

### ISSUE THREAD

**Issue by blakebarnett** [crossplane-contrib/provider-upjet-aws#748]
### What happened?

Apparently [TopicRule clientProperties](https://marketplace.upbound.io/providers/upbound/provider-aws-iot/v0.36.0/resources/iot.aws.upbound.io/TopicRule/v1beta1#doc:spec-forProvider-kafka-clientProperties) have no schema, and changes to them aren't noticed.

### How can we reproduce it?

Create a TopicRule with `clientProperties` for any TopicRule type (we are using Kafka), and then modify them.

### What environment did it happen in?

* Crossplane Version: 1.11.4
* Provider Version: v0.32.1
* Kubernetes Version: v1.24.13-eks-0a21954
* Kubernetes Distribution: EKS

**Comment by turkenf** [comment]
Hi @blakebarnett,

Thank you for raising this issue. Could you please ensure more information(e.g. examples you use) to reproduce the bug?

**Comment by mbbush** [comment]
[topicrule.yaml.txt](https://github.com/upbound/provider-aws/files/12156308/topicrule.yaml.txt)
[role.yaml.txt](https://github.com/upbound/provider-aws/files/12156309/role.yaml.txt)

To reproduce, first enter your own AWS account id in the topicrule.yaml. 

```
kubectl apply -f role.yaml
kubectl apply -f topicrule.yaml
```
Apply is successful, and the Managed Resource becomes ready

`kubectl edit topicrule kafka-topic-rule` and change any field inside `spec.forProvider.kafka[0]`

The Managed Resource remains ready and synced, but the aws resource is never updated to the new state, and the `status.conditions` include 
```
  - lastTransitionTime: "2023-07-25T01:54:54Z"
    message: "apply failed: replacing IoT Topic Rule (some_rule): InvalidParameter:
      3 validation error(s) found.\n- missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.ClientProperties.\n-
      missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.DestinationArn.\n-
      missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.Topic.\n: "
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
```

Terraform suffers from the [same bug](https://github.com/hashicorp/terraform-provider-aws/issues/24742).

**Comment by turkenf** [comment]
Thank you @mbbush, it can be reproduced with the information provided:
```
    Message:               apply failed: replacing IoT Topic Rule (some_rule): InvalidParameter: 3 validation error(s) found.
- missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.ClientProperties.
- missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.DestinationArn.
- missing required field, ReplaceTopicRuleInput.TopicRulePayload.Actions[1].Kafka.Topic.
```
