### ISSUE TITLE
Almost all resources are missing connection details written by writeConnectionSecretToRef

### ISSUE THREAD

**Issue by ItielOlenick** [crossplane-contrib/provider-upjet-aws#767]
### What problem are you facing?

how are resources created by crossplane / upbound AWS provider supposed to be used by k8s deployments if `writeConnectionSecretToRef` will write an empty secrets for all but 5 resources? 

For instance, a s3 bucket is created and a deployment needs to use it's name as an environment variable (from a config map). How can that be done? shouldn't all resources have `writeConnectionSecretToRef` creating secrets with the ARNs, URLs or names populated where applicable?

### How could Official AWS Provider help solve your problem?

Add the missing code for `writeConnectionSecretToRef` in all resources configs.

As seen in https://github.com/search?q=repo%3Aupbound%2Fprovider-aws%20r.Sensitive.AdditionalConnectionDetailsFn&type=code The function `r.Sensitive.AdditionalConnectionDetailsFn` needs to be implemented to populate the secrets.

I would love to contribute to this effort if that is the way to go.

**Comment by mbbush** [comment]
> For instance, a s3 bucket is created and a deployment needs to use it's name as an environment variable (from a config map). How can that be done?

Generally I accomplish this by patching from the relevant `status.atProvider` field to my composite resource, and from there to the other resource where I want to use it, with a `fromFieldPath: Required` policy, which ensures that the second patch doesn't complete until after the first one has happened.

**Comment by ItielOlenick** [comment]
That's the workaround we use to acheive that as well, but it is a workaround, which isn't documented anywhere.

From Crossplane's documentation:

"**writeConnectionSecretToRef**
When a Provider creates a managed resource it may generate resource-specific details, like usernames, passwords or connection details like an IP address.

Crossplane stores these details in a Kubernetes Secret object specified by the writeConnectionSecretToRef values."

This is an essential part of crossplane, and eveyone I know that uses crossplane has dreaded over this.

**Comment by ezgidemirel** [comment]
Hi @ItielOlenick, Upjet based providers like provider-aws automatically generate connectionDetailsSecret information from Terraform's sensitive data fields. You can find which fields are marked as sensitive from this [file](https://github.com/upbound/provider-aws/blob/main/config/schema.json). 

As you pointed out, we can extend this list by implementing `AdditionalConnectionDetailsFn` functions. This is especially helpful when we want to set an API between provider-aws resources and other provider resources like provider-sql through connectionDetails secrets.

Even though we have this automation to determine connectionDetails and there is a way to extend them, I still believe that we can improve user experience with a way to configure them in runtime. This will eliminate status patches and people will no longer need to implement AdditionalConnectionDetailsFn and wait for their changes to be released.

**Comment by ItielOlenick** [comment]
I'd love to contribute to the effort of making this addition.
In the meanwhile I added https://github.com/upbound/provider-aws/pull/769 for sqs, and if that's approved I'd start adding more connection details for other services.
