### ISSUE TITLE
AWS RDS Cluster scaling-compute API call sends incorrect request parameter

### ISSUE THREAD

**Issue by desaidipen** [crossplane-contrib/provider-upjet-aws#794]
### What happened?
* Changing `dbClusterInstanceClass` to a new value for RDS Clusters triggers an API call with incorrect parameter.

### How can we reproduce it?
* Create an RDS cluster (via Claim-Composition or via Managed Resource route) (I have tried PostgresQL and MySQL db engine types).
* Once cluster is fully provisioned, change 'dbClusterInstanceClass' parameter to a new value.  (i changed instance class from db.r6db.xlarge to db.m5d.large).
* This will trigger an API call, but it has incorrect parameters passed, which will result in error and constant failed reconciliation.
* Error and incorrect request parameters.
*     "errorCode": "InvalidParameterCombinationException",
    "errorMessage": "Cannot find upgrade target from 8.0.32 with requested version db.r6gd.large.",
    "requestParameters": {
        "dBClusterIdentifier": "dd-managed-cluster",
        "applyImmediately": true,
        "allowMajorVersionUpgrade": false,
        "allowEngineModeChange": false,
        "engineVersion": "db.r6gd.large" <<< This parameter is mapped incorrectly.
    },
* While if request is submitted via AWS CLI, UI or even via Terraform, it generates correct request and scaling-compute initiates on RDS cluster.
* Correct API Call request parameters.
* "requestParameters": {
        "dBClusterIdentifier": "dd-managed-cluster",
        "applyImmediately": true,
        "allowMajorVersionUpgrade": false,
        "allowEngineModeChange": false,
        "dBClusterInstanceClass": "db.r6gd.large"
    },

### What environment did it happen in?

* Crossplane Version: 1.21
* Provider Version: 0.37
* Kubernetes Version: 1.21 
* Kubernetes Distribution: EKS

**Comment by turkenf** [comment]
Hi @desaidipen, could you please give us more information, example manifests you used, about the changes you made?

**Comment by desaidipen** [comment]
I have tried upgrading RDS (PostgresQL and MySQL) engine version, but it failed.   The claim file used is as below.

`apiVersion: db.test.org/v1alpha1
kind: RelationalDB
metadata:
  name: rds-pgql-a-11
  namespace: team-a
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      environment: dev
      configuration: standard
  clusterNetwork:
    vpcId: vpc-id
    subnetIds:
      - "subnet-001"
      - "subnet-002"
      - "subnet-003"
  resourceConfig:
    providerConfigName: provider-config-irsa
    region: us-east-1
    allocatedStorage: 200
    backupRetentionPeriod: 20
    dbClusterInstanceClass: db.m5d.xlarge >>> After successful deploy change this value to db.r6gd.xlarge.
    iops: 2000
    preferredMaintenanceWindow: "tue:08:00-tue:10:00"
    tags:
      cluster: crossplane
      namespace: team-a
      environment: dev
      application: my-app-1
    # RDS Engine Specific Configurations
    engine: postgres
    engineVersion: "14.8"
    engineFamily: postgres14
    port: 5432
  parameterConfig:
    rds.force_ssl: "1"`

By apply change, we get above cloudtrail api call (with requested parameters) which is incorrect mapping.

**Comment by turkenf** [comment]
@desaidipen it still doesn't seem possible to reproduce this error with the information you provided. As I understand it, you get an error when you change the `dbClusterInstanceClass` parameter in the `apiVersion: rds.aws.upbound.io/v1beta1`, `kind: Cluster` resource.

Could you please give me the full MR, not the claim or composition?

**Comment by desaidipen** [comment]
Sure, here is the yaml file for managed resource.

```apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/cluster
  name: dd-managed-pgql-cluster
  namespace: team-a
spec:
  forProvider:
    dbSubnetGroupName: dd-rds-sng-managed
    manageMasterUserPassword: true
    masterUsername: cpadmin
    region: us-east-1
    skipFinalSnapshot: true
    # ADDITIONAL MANDATORY CONFIG
    allocatedStorage: 200
    backupRetentionPeriod: 7
    dbClusterInstanceClass: db.m5d.xlarge >>> After successful deploy change this value to db.r6gd.xlarge.
    # dbClusterParameterGroupName: default.RDSX.cluster.on
    engine: postgres
    engineVersion: "14.8"
    iops: 5000
    storageEncrypted: true
    storageType: io1
  writeConnectionSecretToRef:
    name: dd-managed-cluster-secret
    namespace: crossplane-system
  providerConfigRef:
    name: provider-config-irsa```

**Comment by turkenf** [comment]
@desaidipen Are you sure that the above MR works in its current state, I get the following error:
```
    message: "apply failed: creating RDS Cluster (dd-managed-pgql-cluster): InvalidParameterCombination:
      The specified DB engine version isn't valid for the postgres DB cluster. Specify
      a valid DB engine version.\n\tstatus code: 400, request id: 78ad87a2-51e7-43fc-8762-cf4440cc4de2: "
```

Just a note: Please ensure that the error can be reproduced with the information you provide when reporting a bug, and clearly state the steps for reproduction.

**Comment by desaidipen** [comment]
@turkenf Here is some additional details.
Crossplane Version: 1.12
Upbound Version: 0.37

> Try: Change engine version to 15.3.

>> If above try does not work, then please create a RDS PostgresQL DB cluster and then try scaling compute.

Observe that reconcile is failing and check API call in Cloudtrail.  It clearly shows that incorrect variable is sent to the api call.
