### ISSUE TITLE
Avoid having the default security group associated with a VPCEnpoint

### ISSUE THREAD

**Issue by ZeBidule** [crossplane-contrib/provider-upjet-aws#796]
### What problem are you facing?

When creating an [AWS VPC endpoint](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/ec2.aws.upbound.io/VPCEndpoint/v1beta1), it automatically attaches the default VPC security group, even if you attach your own security group using [VPCEndpointSecurityGroupAssociation](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/ec2.aws.upbound.io/VPCEndpointSecurityGroupAssociation/v1beta1)

I would like to create a VPCEnpoint that is only attached to a choosen security group and not the default one.

### How could Official AWS Provider help solve your problem?

`security_group_ids `and `securityGroupIdSelector` fields should be proposed as parameter in [VPCEnpoint CRD](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.35.0/resources/ec2.aws.upbound.io/VPCEndpoint/v1beta1) to match [AWS CreateVpcEndpoint API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html). These fields could be optional to use the default security group by default.

The `security_group_ids` in `status` could represent an aggregation of the SG given as parameter + all the SG associated with `VPCEndpointSecurityGroupAssociation` resources.

**Comment by ZeBidule** [comment]
FI, this issue is issued from the following Slack discussion : https://crossplane.slack.com/archives/C05E0UE46S2/p1689845947912269

**Comment by thiagoscodelerae** [comment]
+1
