### ISSUE TITLE
Add docs on migration from monolith provider to provider family

### ISSUE THREAD

**Issue by csantanapr** [crossplane-contrib/provider-upjet-aws#800]
### What problem are you facing?

The README.md doesn't mention provider families

Document a guide that covers steps and considerations when migrating from monolith provider to provider families

Things to consider:
- Doing it in phases, first phase re-use controllerConfig and IAM Role, in next phase create N controllerConfig with N IAM Roles
- Configure controllerConfig and Provider to use IAM Roles (IRSA) for each provider, reuse the controllerConfig in first phase
- Migrate using single IAM Role, in next phase create IAM role per provider family with limited scoped policy
- Service Account for providers have dynamic names for OIDC/trust policy use prefix name in monolith use `provider-aws-*` in provider family be more specific `provider-aws-ec2-*`

**Comment by jeanduplessis** [comment]
@csantanapr there is a manual migration guide available here: https://docs.upbound.io/knowledge-base/migrate-to-provider-families/

And we are in the final stages of polishing up a tool to automate the migration: https://github.com/upbound/docs/pull/174/files

/cc @sergenyalcin for the feedback on things to consider
/cc @turkenf let's update the README with information on the provider family architecture.

**Comment by haarchri** [comment]
released please check: https://docs.upbound.io/providers/migration/#migrating-from-monolithic-to-family-official-providers
