### ISSUE TITLE
TopicRule.iot missing most references from its schema

### ISSUE THREAD

**Issue by mbbush** [crossplane-contrib/provider-upjet-aws#810]
### What problem are you facing?

An AWS IoT Topic Rule is a resource that allows you to choose from a broad menu of supported actions to trigger, each of which trigger a different (generally) aws service. The [schema](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.38.0/resources/iot.aws.upbound.io/TopicRule/v1beta1) for the `TopicRule.iot.aws.upbound.io` only contains the typical `fooRef` and `fooSelector` fields for a single one of those destination types: [SNS](https://marketplace.upbound.io/providers/upbound/provider-aws/v0.38.0/resources/iot.aws.upbound.io/TopicRule/v1beta1#doc:spec-forProvider-sns). 

### How could Official AWS Provider help solve your problem?
I would like to be able to use reference and selector fields for all the fields in the TopicRule schema which reference other resources, and I'm willing to open a PR to make it happen. More broadly, I'd love for it to be easier to get more complete support for references on many resource types. 

I was digging into the implementation details to try and figure out "what's special about the SNS destination" and as far as I can tell, it looks like upjet creates the `fooRef` and `fooSelector` fields automatically *for fields which reference other resources in the examples in the terraform provider docs*, and the [example of `aws_iot_topic_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule) in the terraform docs uses SNS. Once I figured out how to use a local copy of terraform-provider-aws as the source, and edited some of the examples, I was blown away by how much upjet just took care of when I ran `make generate`. 

Is there a way to feed upjet additional examples of terraform code, besides what we scrape from the provider documentation, so we can teach it more about how resources relate, and reuse the powerful codegen capabilities it already has? I would find this much easier than hand-writing a new `config.go` for the resource.

**Comment by turkenf** [comment]
Hi @mbbush, 

Thank you for bringing up this issue, we would appreciate your contributions.
