### ISSUE TITLE
Hardcoded Family Provider Path

### ISSUE THREAD

**Issue by humoflife** [crossplane-contrib/provider-upjet-aws#844]
### What happened?

When provider binaries are served from a private registry other than xpkg.upbound.io, the provider-aws-XYZ cannot resolve the location of the provider-family-aws. The individual provider health will remain unhealthy, unless the dependency checks are disabled. 

It would be useful if providers can be run with dependency checks and if the xpkg.upbound.io/upbound/provider-family-aws can be searched for perhaps both at xpkg.upbound.io/upbound as a fall back, and primarily relative to the location of the other provider-aws-XYZ binaries.

### How can we reproduce it?

Install one of the provider-aws-XYZ, e.g. provider-aws-ec2 from a private repo on a management cluster that is not allowed to access xpkg.upbound.io. The provider health will remain unhealthy until the dependency check has been disabled.

### What environment did it happen in?

* Crossplane Version: 0.13.x
* Provider Version: 0.38.x
* Kubernetes Version:  1.27.x
* Kubernetes Distribution:  EKS

**Comment by haarchri** [comment]
related to https://github.com/crossplane/crossplane/issues/4299

**Comment by tkaesserfm** [comment]
You can try to set `skipDependencyResolution: true` on the family-providers and install the dependency-provider manually

**Comment by tkaesserfm** [comment]
Turns out that was not the whole story, what you need too is a subpath in your registry-path, e.g: 999999999999.dkr.ecr.eu-west-1.amazonaws.com/upbound/provider-family-aws:v0.39.0 

I put more details to https://github.com/crossplane/crossplane/issues/4299

**Comment by humoflife** [comment]
Can the request for non hard coded paths be implemented so that dependency resolution can be applied when obtaining the images from a private repository / registry?
