### ISSUE TITLE
Improve support for AWS GovCloud

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane-contrib/provider-upjet-aws#855]
### What problem are you facing?

Support for AWS GovCloud is lacking in the provider today. We need to implement proper support for it.

Examples of issues users have faced so far:
- https://github.com/upbound/provider-aws/issues/820
- https://github.com/upbound/provider-aws/issues/757

### How could Official AWS Provider help solve your problem?

Implement proper support for GovCloud.

Consider looking at how `crossplane-contrib/provider-aws` deals with this:
- https://github.com/crossplane-contrib/provider-aws/pull/1329
- https://github.com/crossplane-contrib/provider-aws/pull/1364

**Comment by mbbush** [comment]
One difficulty in supporting this using upjet is that when writing an ExternalName configuration, the region is available, but not the partition. 

What if we had an `ARNBuilder` function or something, for use in constructing ARNs, which knew which regions are in which partitions? That could also help DRY up some of the string concatenation used in external name configurations, where we're currently assuming the aws-commercial partition, for e.g. [iam policy](https://github.com/upbound/provider-aws/blob/c1f16051f733c89cac2d7b5c60d337370a1f3ce1/config/externalname.go#L2686), [sns topic](https://github.com/upbound/provider-aws/blob/c1f16051f733c89cac2d7b5c60d337370a1f3ce1/config/externalname.go#L863), [elasticsearch domain](https://github.com/upbound/provider-aws/blob/c1f16051f733c89cac2d7b5c60d337370a1f3ce1/config/externalname.go#L2388C5-L2388C5),   [state functions](https://github.com/upbound/provider-aws/blob/c1f16051f733c89cac2d7b5c60d337370a1f3ce1/config/externalname.go#L1194-L1195), and others

**Comment by jacob-kuder** [comment]
Any update on this?
