### ISSUE TITLE
Unable to use custom launchtemplate with EKS nodegroup

### ISSUE THREAD

**Issue by recht** [crossplane-contrib/provider-upjet-aws#866]
### What happened?

When trying to use a custom launchtemplate for an EKS nodegroup the provider fails with `apply failed: creating EKS Node Group (XXXX): InvalidParameterException: Disk size must be specified within the launch template.`

This seems to be because even if `diskSize` is not set on the nodegroup, it will set a default value, but when using a launchtemplate, that value should not be set at all.

### How can we reproduce it?

Set a launchtemplate in a nodegroup resource.

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: 0.38.0

**Comment by turkenf** [comment]
@recht, please share with us the example MR you used, the steps to create the issue, the expected behavior, and the actual behavior.

**Comment by nello1992** [comment]
When you specify a LaunchTemplate, you have to remove "diskSize" attribute when you define the NodeGroup. Otherwise, the deployment will fail as stated here:
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html
