### ISSUE TITLE
Make it easier to work with IAM policies

### ISSUE THREAD

**Issue by mbbush** [crossplane-contrib/provider-upjet-aws#895]
### What problem are you facing?

When writing a composition using the patch and transform apis, which includes an IAM policy, it is basically impossible to do anything using arrays, as the only tool available is go template string formatting, which does not generate valid JSON. Additionally, the CustomResourceDefinition for the `Policy.iam` managed resource does not provide even partial validation of the policy document. 

### How could Official AWS Provider help solve your problem?

It would be much easier to manage IAM policies in crossplane if I could treat the policy document like an object with a known schema. Then ideally the managed resource could both perform at least some validation, and allow particular fields to be specified individually in patches. This would let me have, for example, an XRD which allows the user to identify which resources they should be able to access, and a composition that can translate that into a valid IAM policy for the particular use case.

I looked around a bit for prior art on this, and was surprised to not find much. I found the [formal grammar definition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html) of an IAM policy, and some "is this a valid IAM policy" validators implemented in python and typescript, but nothing in openapi format or golang. The [aws-controllers-k8s/iam-controller](https://github.com/aws-controllers-k8s/iam-controller/blob/b10b5d932c0ac19e1c38e9efde8eaa64eaa74d3f/config/crd/bases/iam.services.k8s.aws_policies.yaml#L69-L88) seems to just expect a string. 

I'm surprised that nobody seems to have done this yet, which makes me wonder if perhaps there's a good reason not to do it, that's just not obvious to me. 

Perhaps the crux of the issue is that it's hard to be sure that the validations you place on the object definition exactly match the validations done by AWS, by neither allowing invalid policies nor rejecting valid ones. For the crossplane use case, we could retain the original string field (which would be required for backwards compatibility anyways) and just have a new `policyObject` or `policyYaml` field which, if defined, validates itself and writes its value to the existing `spec.forProvider.policy` string field, which would relax the "must not reject any valid IAM policy" requirement a bit, since edge cases could be handled by the string field.

I would implement this just for the `Policy.iam.aws.upbound.io` resource to start, with the possibility of extending it to other `iam` resources and/or to certain resource based policies like role trust policies or KMS key policies in the future.

This seems somewhat related to #509, but it seems like it would be simpler to just use the existing JSON definition of an IAM policy than to import the terraform `iam_policy_document`.

**Comment by alex-souslik-hs** [comment]
Personally I find the JSON easier to manage, but it's probably good to have both options
