### ISSUE TITLE
Request for `aws_msk_serverless_*` resource

### ISSUE THREAD

**Issue by nalbury** [crossplane-contrib/provider-upjet-aws#902]
### What resource do you need?

Terraform Resource Name: 

There's a couple resources required for MSK serverless operation:
- [x] [aws_msk_serverless_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_serverless_cluster.html)
- [ ] [aws_msk_cluster_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster_policy)

### What is your use case?

We've started implementing crossplane and have a requirement from the org to support MSK serverless. 

FWIW I started making an attempt at this myself an am happy to continue with it, but I noticed that the auto generated code I got after moving the `aws_msk_serverless_cluster` to `externalname.go` was under the "msk" API vs the existing Kafka API, is there any way to explicitly set that? 

Thanks in advance!

**Comment by nalbury** [comment]
Opened https://github.com/upbound/provider-aws/pull/905 which should add `aws_msk_serverless_cluster` if I understand the contributor docs correctly 🤞

**Comment by rahul-theorem** [comment]
We're interested in using `aws_msk_vpc_connection` alongside `aws_msk_cluster_policy` to set up MSK access w/ privatelink. I'm happy to track a separate issue for `aws_msk_vpc_connection` if you're already looking at adding the cluster policy managed resource.

**Comment by nalbury** [comment]
Yup, figuring things out with the serverless cluster resource right now but was going to tackle `aws_msk_cluster_policy` next.

**Comment by turkenf** [comment]
I'm reopening the issue because the `aws_msk_cluster_policy` resource has not been tested yet.

**Comment by nalbury** [comment]
Will be starting that PR today. Thanks again @turkenf

**Comment by nalbury** [comment]
Unfortunately, I don't know if we can add the `aws_msk_cluster_policy` with the current version of the terraform provider in use. The resource wasn't supported by the AWS terraform provider until [version `5.13.0`](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.13.0). 

Out of curiosity, are there plans to upgrade to v5 of the provider in the near future?

**Comment by turkenf** [comment]
With this [PR](https://github.com/upbound/provider-aws/pull/864), the terraform version will be upgraded to 5.19.0 in the coming days.
