### ISSUE TITLE
Request for `il-central-1` AWS region support

### ISSUE THREAD

**Issue by halversonea** [crossplane-contrib/provider-upjet-aws#924]
### What resource do you need?

Region il-central-1

### What is your use case?
This is a new AWS region and is not supported yet. "Invalid AWS Region"

**Comment by jaredhancock31** [comment]
I'm also blocked by this.

**Comment by jeanduplessis** [comment]
@halversonea @jaredhancock31 we are bumping the Terraform AWS provider in the next release of this provider which will bring support for this region: https://github.com/hashicorp/terraform-provider-aws/issues/32795
