### ISSUE TITLE
Node role taking precedence despite IRSA config

### ISSUE THREAD

**Issue by arichtman-srt** [crossplane-contrib/provider-upjet-aws#945]
Hi all - my AWS S3 provider seems to be assuming the node role, rather than taking the IRSA.
I've checked the following:

- ControllerConfig is to spec
- ProviderConfig is to spec
- S3 provider spec references the ControllerConfig
- AWS family provider spec references the ControllerConfig
- S3 controller pod has service account bound
- AWS family pod has service account bound
- S3 service account has EKS role annotation
- AWS family service account has EKS role annotation
- Bucket resource spec references the ProviderConfig

### What happened?

S3 bucket could not be created, AccessDenied errors.

### How can we reproduce it?

I've captured everything from kubernetes directly, to ensure it's _exactly_ what the cluster had.
You can see it here: https://gist.github.com/arichtman-srt/a845f42a85136a3b875a8a60146fa537

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: aws-s3:v0.43.0
* Kubernetes Version: Client Version: v1.28.3, Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3, Server Version: v1.27.6-eks-f8587cb
* Kubernetes Distribution: EKS

### References

- https://docs.upbound.io/providers/provider-aws/authentication/#iam-roles-for-service-accounts
- https://github.com/upbound/provider-aws/blob/main/AUTHENTICATION.md

**Comment by chlunde** [comment]
Looks like the bucket `platform-demo-bucket-srt` already exists, either you created it or someone else. Try adding some random characters to the name?

Also, check the environment variables of the pod to ensure that IRSA is working correctly, most likely it's not set correct. Maybe restart the pod if the SA annotations are recently created/modified.

Regarding precedence, skimming the code, it looks like "IRSA" is actually "let the SDK automatically setup auth" while WebIdentity explicitly uses WebIdentity which is what IRSA uses:
https://github.com/upbound/provider-aws/blob/c1f16051f733c89cac2d7b5c60d337370a1f3ce1/internal/clients/provider_config.go#L321-L353

I would also suggest securing the node with IMDSv2 and to ensure containers cannot assume the node role.
