### ISSUE TITLE
Compatibility matrix for provider-family-aws with provider-aws-*

### ISSUE THREAD

**Issue by sathyanarays** [crossplane-contrib/provider-upjet-aws#956]
Hello team,
Is there any prescribed compatibility matrix for determining the compatibility between the `provider-family-aws` with other aws providers such as `provider-aws-s3` and `provider-aws-dynamodb`?

For example, how do we evaluate if the following installations of providers is valid and work fine?

```
NAME                          INSTALLED   HEALTHY   PACKAGE                                                 AGE
upbound-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v0.37.0     72m
provider-aws-dynamodb         True        True      xpkg.upbound.io/upbound/provider-aws-dynamodb:v0.37.0   72m
provider-aws-s3               True        True      xpkg.upbound.io/upbound/provider-aws-s3:v0.43.0         72m
```

This would help the community to determine the upgrade path for each of these providers.

**Comment by devops-inthe-east** [comment]
Hey, Any luck figuring this out,

**Comment by jeanduplessis** [comment]
@devops-inthe-east while you should be able to rely on semver versioning where all minor/patch releases are compatible with each other, our recommendation is to keep your versions in sync as a good practice to adhere to.

**Comment by pierluigilenoci** [comment]
@jeanduplessis Unfortunately, it is not that easy to keep the versions aligned unless you [manually install](https://github.com/crossplane-contrib/provider-upjet-aws/issues/1088#issuecomment-1896018221) the family provider. And if you do this in a cluster with the providers already installed, a [bug](https://github.com/crossplane-contrib/provider-upjet-aws/issues/1452) prevents a clean cluster, at least as far as I know.

**Comment by pierluigilenoci** [comment]
I found a way to align the versions of the various AWS family providers.
The instructions are split between two threads:
- https://github.com/crossplane-contrib/provider-upjet-aws/issues/1088
- https://github.com/crossplane-contrib/provider-upjet-aws/issues/1452

**Comment by jeanduplessis** [comment]
To understand what Upbound recommends from a compatibility pov and what we support our customers on see this section in our docs: https://docs.upbound.io/providers/policies/#compatibility
