### ISSUE TITLE
Request for `aws_codeguruprofiler_profiling_group` resource

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-upjet-aws#959]
### What resource do you need?

Terraform Resource Name: 
* `aws_codeguruprofiler_profiling_group`

Depends on https://github.com/hashicorp/terraform-provider-aws/issues/16768

### What is your use case?
Help Java-developers diagnose performance issues.

```[tasklist]
### Tasks
```

**Comment by chlunde** [comment]
I'm looking at adding this to upstream - currently blocket on https://github.com/hashicorp/terraform-provider-aws/pull/34355

But will this be a dedicated provider for basically one or two resources under the codeguruprofiler API? Or do you ever merge resources @turkenf ?

**Comment by turkenf** [comment]
> But will this be a dedicated provider for basically one or two resources under the codeguruprofiler API? Or do you ever merge resources @turkenf ?

No resources from this API group have been added yet, so yes there will be a new family provider containing the relevant resources.
