### ISSUE TITLE
Providers Unhealthy after upgrade

### ISSUE THREAD

**Issue by r2ronoha** [crossplane-contrib/provider-upjet-aws#964]
### What happened?
After upgrading the providers, they become unhealthy because the providerrevision is unable to take ownership of existing resources
```
Warning  SyncPackage          3s                 packages/providerrevision.pkg.crossplane.io  cannot establish control of object: rolepolicies.iam.aws.upbound.io is already controlled by ProviderRevision provider-aws-iam-ebb7af6959e9 (UID e90b66bb-9a03-4634-aafd-f21ff2c37972)
```
There is a process that can be performed with manual deletion of resources and crds, but that is neither scalable nor valid for a production environment

### How can we reproduce it?
Install provider-aws-xxx to an older version via helm
Upgrade the provider version in the chart (and required changes)
Roll out

### What environment did it happen in?

* Crossplane Version: 1.14.0
* Provider Version: 0.41.0 -> 0.43.1
* Kubernetes Version: `Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3-eks-4f4795d", GitCommit:"e77944ea667aee90c84c48a74a2a0da7a23e0508", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:39Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes Distribution: EKS

**Comment by dmaggi** [comment]
Any update on how to solve this issue?

**Comment by r2ronoha** [comment]
I haven't received any response. We moved away from Crossplane in the end as it does not fit our needs
