### ISSUE TITLE
provider-aws-s3 bucket examples incorrect

### ISSUE THREAD

**Issue by humoflife** [crossplane-contrib/provider-upjet-aws#988]
### What happened?

Bucket [examples](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v0.44.0/resources/s3.aws.upbound.io/Bucket/v1beta1) produce the following error message:

The Bucket "example-${Rand.RFC1123subdomain}" is invalid: metadata.name: Invalid value: "example-${Rand.RFC1123Subdomain}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

### How can we reproduce it?

Apply one of the examples from [here](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v0.44.0/resources/s3.aws.upbound.io/Bucket/v1beta1) and receive the error.

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by stevendborrelli** [comment]
Those are uptest markers (see https://github.com/upbound/uptest#injecting-dynamic-values-and-datasource). 

I agree it should be better documented.
